### ISSUE TITLE
Mixed OpenAddresses imports with unmatched data in search results

### ISSUE THREAD

**Issue by migurski** [pelias/pelias#268] opened 2016-02-24 16:20 UTC
I think these two are the same address, but they’re showing up with different IDs and different encodings:

<img width="506" alt="screen shot 2016-02-24 at 11 09 47 am" src="https://cloud.githubusercontent.com/assets/58730/13292102/7ec2d17e-dae8-11e5-94bb-6b0b1931da8a.png">

<img width="507" alt="screen shot 2016-02-24 at 11 09 55 am" src="https://cloud.githubusercontent.com/assets/58730/13292106/80cdecf6-dae8-11e5-89e4-428e51355cf6.png">

**Comment by riordan** [comment] 2016-02-25 21:36
We'll dig into it.

**Comment by orangejulius** [comment] 2016-02-26 19:49
I looked into this yesterday and after importing all of the Czech Republic onto my local machine, I couldn't reproduce the issue. It's still happening on our dev server though. Next step for me is to see if it magically goes away in the next build.

There are 3 lines with exactly the same data for that address in the OA file for CZ though...

**Comment by riordan** [comment] 2016-04-13 15:15
This looks like it's been fixed by switching to the WoF admin lookup

**Closed** 2016-04-13 15:15 UTC
Labels: addresses
