### ISSUE TITLE
search in leaflet plugin cannot find Victoria, British Columbia

### ISSUE THREAD

**Issue by burritojustice** [pelias/pelias#129] opened 2015-09-22 23:13 UTC
Victoria is the provincial capital. Doesn't come up in multiple search attempts: 

Victoria (another Victoria in Canada comes up...)
Victoria BC (Germany up first, then random POIs)
Victoria, British Columbia (province of BC comes up, along with places in Vancouver)

**Comment by missinglink** [comment] 2015-09-25 12:35
investigation: (based off the latest dev branch)

expected: 'Victoria' city in the province of 'British Columbia' in 'Canada' to appear in top 10 results
ref: https://en.wikipedia.org/wiki/Victoria,_British_Columbia

---

search term "Victoria"

```
/autocomplete
 1)	Victoria, Tamaulipas
 2)	Victoria, Australia
 3)	Victoria, Guanajuato
 4)	Villa Victoria, México
 5)	Victoria Park, Western Australia
 6)	Victoria Plains, Western Australia
 7)	Victoria County, TX
 8)	Victoria East, EASTERN CAPE
 9)	Guadalupe Victoria, Puebla
10)	Salinas Victoria, Nuevo León

/search
 1)	Victoria, Australia
 2)	Victoria, Tamaulipas
 3)	Victoria, Guanajuato
 4)	Villa Victoria, México
 5)	Victoria Park, Western Australia
 6)	Victoria Plains, Western Australia
 7)	Victoria County, TX
 8)	Victoria East, EASTERN CAPE
 9)	Guadalupe Victoria, Puebla
10)	Salinas Victoria, Nuevo León
```

---

search term "Victoria, British Colombia, Canada"

```
/autocomplete
 1)	British Columbia, Canada
 2)	Virginia Beach City, VA
 3)	Birgu (citta' Vittoriosa), Malta
 4)	Colombia
 5)	Van Buren County, MI
 6)	Canada Bay
 7)	Victoria, Tamaulipas
 8)	Victoria, Australia
 9)	Victoria County, TX
10)	British Virgin Islands

/search
 1)	Victoria, Australia
 2)	Victoria, Tamaulipas
 3)	Victoria, Capital, British Columbia
 4)	Victoria, Greater Vancouver, British Columbia
 5)	Victoria, VICTORIA, British Columbia
 6)	Victoria, VANCOUVER, British Columbia
 7)	Victoria, Guanajuato
 8)	Villa Victoria, México
 9)	6 Victoria Street, KAMLOOPS, British Columbia
10)	Victoria Park, Western Australia
11)	Victoria, Caldas
```

**Comment by missinglink** [comment] 2015-09-25 12:49
there are a few issues going on here, the obvious one is that `Victoria` is a common name and so is also a very common place name, and because of `Queen Victoria` it's ubiquitous! in Mexico `Guadalupe Victoria` is the eponym.

looking over the list for the input "Victoria" I see "Victoria, Australia" which is an Australian state and so I would expect to rank higher (it should really be the first result), the Mexican city of "Ciudad Victoria" is actually less populous and so I would expect to rank lower than "Victoria BC" and then the others are less 'important', Canada doesn't even make the top 10 list for "Victoria" which I agree is an error.

looking over the list for the fully specified input "Victoria, British Colombia, Canada" I can see pretty a big difference for `/autocomplete`, the matching here is not accounting for the "," delimiter in the input text and so is treating all tokens equally, this is an error. The weird thing is the top result is "British Columbia, Canada" which is not a terrible match here, "British Virgin Islands" makes an appearance when there are probably better matches to return.

So... I'd say the real issue is that the record simply doesn't exist in our data sets, it's unusual to not find what you are looking for when fully specifying the input text. It's possibly that it's indexed under a more formal 'official' name (eg. 'The city and county of the city of London') or that it just doesn't exist.

**Comment by missinglink** [comment] 2015-09-25 13:02
[edit], I think this is the record you are looking for? it's in the geonames dataset.

```javascript
{
  "type": "Feature",
  "properties": {
    "id": "6174041",
    "gid": "gn:locality:6174041",
    "layer": "locality",
    "source": "gn",
    "name": "Victoria",
    "country_a": "CAN",
    "country": "Canada",
    "region": "British Columbia",
    "county": "Capital",
    "locality": "VICTORIA",
    "confidence": 0.737,
    "label": "Victoria, VICTORIA, British Columbia"
  },
  "geometry": {
    "type": "Point",
    "coordinates": [
      -123.3693,
      48.43294
    ]
  }
}
```

**Comment by nvkelso** [comment] 2015-09-25 19:22
Because Who's On First concords Quattroshapes polygon for Victoria with GeoName's population?

Pelias already knows the GeoNames.org bits. Shouldn't an admin-1 (region) capital win over almost all the rest of these? And searching from SF it's the nearest & most kindred.

**Comment by dianashk** [comment] 2015-09-25 22:26
@nvkelso, it doesn't look like @burritojustice's query specifies a geo-bias, so we have no indication that the search is being performed from SF. It could make sense to boost different admin layers with an ascending value, where country gets highest boost, and neighbourhood gets the lowest. I believe at this point we boost all admin layers equally + sqrt(popularity).

**Comment by missinglink** [comment] 2015-10-13 16:10
this is now fixed: `text=Victoria`:

```
 1)	Victoria, Australia
 2)	Victoria, VICTORIA, Canada
```

regression test added: https://github.com/pelias/acceptance-tests/blob/master/test_cases/autocomplete_admin_areas.json#L86-L103

**Closed by missinglink** 2015-10-13 16:10 UTC
