### ISSUE TITLE
Charlotte, NC and Toledo, OH cannot be found using /v1/autocomplete

### ISSUE THREAD

**Issue by simonw** [pelias/pelias#684] opened 2017-11-14 19:38 UTC
This autocomplete search for `charlotte nc` against `locality,region,borough` returns 0 results:

http://search.mapzen.com/v1/autocomplete?sources=wof&layers=locality,region,borough&api_key=mapzen-xxx&text=charlotte+nc

I cannot find a search term that returns Charlotte NC.

**Comment by simonw** [comment] 2017-11-14 19:39
Charlotte is indeed a locality in Who's On First: https://whosonfirst.mapzen.com/spelunker/id/85981333/

**Comment by simonw** [comment] 2017-11-14 19:41
Note that running this against `/v1/search` instead DOES return the correct result - so this is an autocomplete bug.

**Comment by simonw** [comment] 2017-11-14 19:56
Same exact problem for `Toledo OH` - 0 results from `/v1/autocomplete`, correct results for `/v1/search`

**Comment by orangejulius** [comment] 2017-11-14 20:05
Hey @simonw,
Thanks for writing in. Autocomplete issues when searching for administrative areas are pretty well known. Fortunately, we are working on improvements to [Placeholder](https://github.com/pelias/placeholder), our admin area lookup engine, that should help.

Its good timing really, as the first set of changes are [under review](https://github.com/pelias/placeholder/pull/70) right now. They appear to get both Charlotte and Toledo correct! Thanks for the test cases :)

![image](https://user-images.githubusercontent.com/111716/32801970-aa82a038-c94c-11e7-93f4-d5484446ccf5.png)
![image](https://user-images.githubusercontent.com/111716/32802153-3426ce2c-c94d-11e7-9347-24364a7d1cdf.png)


If you want to test out other cases, I just followed along from the instructions in the placeholder readme regarding how to build the placeholder database, and it worked great (it took about 3 hours to build). We will keep you updated as it gets closer to release. Let us know if you have any other questions!

**Comment by trescube** [comment] 2017-11-14 20:14
@orangejulius is correct, autocomplete is a bit lacking, especially when punctuation is missing.  Placeholder will resolve these issues.  

If you were to put a comma between "Toldeo" and "OH", then it would work.  This is a drawback of the [addressit](https://github.com/DamonOehlman/addressit) parser which relies on comma delimiters between address components.

**Comment by orangejulius** [comment] 2017-11-14 20:15
Oh you know what also contributes? At least for Charlotte, we don't import any population values, because none of these properties are non-zero:

```
  'mz:population',
  'wof:population',
  'wk:population',
  'gn:population',
  'gn:pop',
  'qs:pop',
  'qs:gn_pop',
  'zs:pop10',
  'meso:pop',
  'statoids:population',
  'ne:pop_est'
```

@nvkelso would that be considered a WOF data issue or are we missing some valid fields?

**Comment by simonw** [comment] 2017-11-14 21:36
This bug is affecting our users right now - we're getting complaints from people in Charlotte and Toledo that they can't find their city through our search feature.

If this is a bug relating to the missing population fields, do you think this might end up being a quick fix? If the fix will take more than a day we will look into implementing a workaround at our end (possibly involving making a call to `/v1/search` if we get back 0 results from `/v1/autocomplete).

**Comment by orangejulius** [comment] 2017-11-14 22:29
Unfortunately its not really a quick fix as our data imports take a little under two days. We run them regularly though so as soon as the data changes are in they will start making their way out towards Mapzen Search production. If you have more questions about that please don't hesitate to email support@mapzen.com. Lets keep this issue focused on the Pelias open source project.

As for falling back to search if autocomplete returns no results there are problems with approach. The biggest one is that search is not partial-match aware. For example, by design, with the query `lond` you get [Lond, Pakistan](http://pelias.github.io/compare/#/v1/search%3Ftext=lond) back from search and [London, England](http://pelias.github.io/compare/#/v1/autocomplete%3Ftext=lond) from autocomplete. It's an extreme example but illustrates the problem.

What you _can_ (and in fact should) do is trigger a request against the search endpoint when the user hits enter, and otherwise query autocomplete. In our experience users more or less intuitively know to type and if you don't get anything good hit enter when you're done.

With that approach you get the partial-match awareness of autocomplete as the user types, and if they have to type a full query for whatever reason, they will most likely eventually hit enter and get what they want from search.

**Comment by nvkelso** [comment] 2017-11-17 20:58
@stepps00 Can you take a look at this, please? Research the expected population values for the two localities and update using Boundary Issues.

**Comment by stepps00** [comment] 2017-11-17 21:40
I just updated the records of [Toledo](https://whosonfirst.mapzen.com/spelunker/id/101712039/) and [Charlotte](https://whosonfirst.mapzen.com/spelunker/id/85981333) in Boundary Issues with new population data. I'll update this comment with the commits once they are merged.

**Comment by simonw** [comment] 2017-11-20 19:39
I'm still seeing these cities missing from the autocomplete API results despite the above fix to the population properties - will the population fix cause the autocomplete API to be fixed any time soon?

**Comment by orangejulius** [comment] 2017-11-20 21:20
Hi @simonw,
We've just pushed a new data build to Mapzen Search production and searches for [Charlotte](http://pelias.github.io/compare/#/v1/autocomplete%3Fsources=wof&layers=locality,region,borough&text=charlotte,%20north%20carolina) and [Toledo](http://pelias.github.io/compare/#/v1/autocomplete%3Fsources=wof&layers=locality,region,borough&text=toledo,%20oh) with layer restrictions like your queries above are now working! Thanks for your patience.
![image](https://user-images.githubusercontent.com/111716/33042109-b586797a-ce0e-11e7-9d5a-8efb1728d6d6.png)

I think we're all done here, but feel free to reach out with questions or if anything else seems wrong.

**Closed by orangejulius** 2017-11-20 21:20 UTC
