### ISSUE TITLE
507 POWERS AV, port orange, fl 32127

### ISSUE THREAD

**Issue by b-may** [pelias/pelias#447] opened 2016-10-19 19:01 UTC
Hey team! 

I was using your awesome geocoding engine when I noticed something interesting.
Let me tell you more about it.

---
#### Here's what I think could be improved :trophy:

If I take out the city name, e.g. http://pelias.github.io/compare/#/v1/search%3Ftext=507%20POWERS%20AV,%20fl%2032127
its the same result.

If I remove city and state, e.g. http://pelias.github.io/compare/#/v1/search%3Ftext=507%20POWERS%20AV%2032127
it works correctly.

**Comment by trescube** [comment] 2016-10-19 19:11
It looks like libpostal parses the input correctly but we're not finding it because the name of the street can't be found with `Powers Av`.  Updating to `Powers Ave` or `Powers Avenue` finds a result.  Removing city and state causes Pelias to fallback to the old behavior of just matching on tokens.

**Comment by b-may** [comment] 2016-10-19 19:25
Interesting. The odd thing is it works with `Powers Av` without the city, state name but using zip code.

Also, I thought pelias could handle common street suffix abbreviations. 

Here's another one:

`2801 fieldstone ct, orlando, fl` which doesn't work. And yes, `2801 fieldstone court, orlando, fl` works. Isn't Ct pretty common abbreviation for court?

This works too! `2801 fieldstone ct 32839`

**Comment by b-may** [comment] 2016-10-19 19:32
Here's another one, this time no abbreviation issues:

Doesn't work right: `304 bloomingfield drive, brandon, FL 33511`

Works correctly: `304 bloomingfield drive 33511`
This works, too! `304 bloomingfield`

That last one shows just how strong of an influence the street number has.

**Comment by trescube** [comment] 2016-10-19 19:36
With just `Powers Av`, pelias falls back to the old production behavior that emphasized less on geocoding and more on just finding documents that matched terms.  Pelias does match on common street type abbreviations which is why it works with `Ave` when the actual word is `Avenue`.  We'll look into adding `Av` as a street suffix.  

According to [the street suffixes files](https://github.com/pelias/schema/blob/master/street_suffix.js), we have the `Court`->`Ct` abbreviation disabled since it can conflict with the abbreviation for Connecticut.  That decision needs to be revisited as we transition towards a true geocoding service.  

Much like `507 POWERS AV 32127`, `2801 fieldstone ct 32839` falls back to the seemingly-more-accurate-but-returns-unrelated-results search.

**Comment by trescube** [comment] 2016-10-19 19:40
`304 bloomingfield drive, brandon, FL 33511` doesn't work because `304 bloomingfield drive` is in Bloomingdale, FL, not Brandon, FL.  According to our blog post on [changes to search](https://mapzen.com/blog/the-next-chapter-of-search/), Pelias now uses fallback behavior where if the housenumber+street can't be found in the supplied city+state, results for the city+state will be returned.

**Comment by orangejulius** [comment] 2016-10-19 19:43
That last one appears to be because we show the city as Bloomingdale, FL: 
![screenshot_2016-10-19_15-35-44](https://cloud.githubusercontent.com/assets/111716/19534428/b996ccda-9611-11e6-8172-2c655c36fc05.png)

It probably ties into issues related to [postal cities](https://github.com/pelias/pelias/issues/396) and other admin lookup related things. 

With the recent changes, in general pelias is a lot more strict, because our text parsing is now good enough to be that strict. Of course, when it fails, it's going to fail more noticeably, rather than just returning a few results that aren't quite as good as they might have been. But we can actually go through and fix all these bugs now, rather than try to tweak a system that isn't actually capable of getting as good as we eventually want it to be.

**Comment by b-may** [comment] 2016-10-19 20:13
OK, now I'm starting to get the behavior. I read the blog post, too. It seemed to be working pretty well before the change! But I get what you guys are doing, you have to make sure the foundation is rock solid, etc.

I am seeing a lot of examples where the city name is not agreeing with your database, i.e. the postal cities problem. IMHO, heavy weight should be given to the city + state + zipcode combo that matches USPS data (and most likely most OA data). 

Using `304 bloomingfield drive, brandon, FL 33511` as an example again, if you go to usps.com and look up valid cities for 33511, you get Brandon. If you search the Hillsborough County Property Appraiser data on site address city name for Bloomingdale - zero results. 

So, I know you can't get a data dump from USPS. But the next best thing is OA, right? The OA source (at least in FL) is from county government site address points and parcel centroids with site address info. These are all geared towards postal addresses, and that is how people search for stuff.

I also understand the need to have multiple admin names for a given area, and the usps handles it by providing alternate city names. But its all tied to the zip code polygons. To me, that is a good way to go. And if then no city name match, go with the locality names. From what I have seen, there's a ton of locality names that should not be given much weight at all. For example, down the street there may be one called Gomez, but no body ever says hey so and so is on X street in Gomez, they say X street in Palm City.

How can I help further flesh out this problem? Provide a list of more examples where this is an issue?

**Comment by b-may** [comment] 2016-10-20 02:00
Looking further into this - its really problematic. It appears that Census Designated Places are what is being used as a proxy for city boundaries, right? This falls apart when there is no CDP. This is why using zip codes as the main "place" geography and associating one or more city names with it is better, IMHO.

Example: `2807 Southeast DELMAR Street, stuart, fl 34997` - this is the official address. But pelias can't find it. The only way it can be found is by substituting martin county for the city name, or dropping the city name, e.g. `2807 Southeast DELMAR Street, 34997` or dropping city/state/zip, e.g. `2807 Southeast DELMAR Street` 

No one ever thinks to search for an address using the county name instead of the city name. 

At this point, the only thing guaranteed to work (in Florida) is don't use a city name, instead use a zip code. IMHO, that is very counter-intuitive to not use the official city name in an address search.

**Comment by orangejulius** [comment] 2019-03-28 19:21
I've moved all examples from this issue into https://github.com/pelias/pelias/issues/396#issuecomment-477736197, and most of them show improvement after https://github.com/pelias/wof-admin-lookup/pull/232.

To reduce issue noise, I'll close this as a dupe of #396. Thanks for the report. It took us a while but all the examples were very helpful :)

**Closed by orangejulius** 2019-03-28 19:21 UTC
Labels: outreach
