### ISSUE TITLE
Data present in source data but not queryable

### ISSUE THREAD

**Issue by NickStallman** [pelias/pelias#754] opened 2018-10-28 22:26 UTC
Hey team! 

What's the correct debugging process to determine why an address can be found in the source data but not appear when queried in Pelias?
I've come across a specific example that I found in OpenAddresses but not my own database. I tried rebuilding my database with no luck and it's also not found in geocode.earth either.

---
#### Here's what I did :innocent:
https://pelias.github.io/compare/#/v1/search%3Ftext=22%20HENSON%20STREET,%20MARRICKVILLE%20,NSW,2204

---
#### Here's what I got :scream_cat:
Fallback to MARRICKVILLE ,NSW,2204
The address is parsed perfectly so no issue there, just zero exact matches.

---
#### Here's what I was expecting :sparkles:
The source data clearly has an exact matching record:

`/mnt/data/openaddresses/au# grep -i Henson countrywide.csv | grep -i Marrickville | grep ,22,
151.1437656,-33.9160777,22,HENSON STREET,UNIT 1,MARRICKVILLE,,NSW,2204,GANSW711430357,b14af95eebac649e
151.1437656,-33.9160777,22,HENSON STREET,UNIT 2,MARRICKVILLE,,NSW,2204,GANSW711421249,9a0600214aad0197
151.1437656,-33.9160777,22,HENSON STREET,,MARRICKVILLE,,NSW,2204,GANSW705321300,310f9c4bd150b38f`

---
#### Here's what I think could be improved :trophy:
a) Specifically any clues why this address refuses to be matched
b) I couldn't find any general troubleshooting steps for identifying and resolving issues like this.

**Comment by missinglink** [comment] 2018-10-29 20:13
I suspect that the address was correctly imported but that the locality name differs from the one specified in the CSV file.

[This query](https://pelias.github.io/compare/#/v1/search%3Ftext=22%20HENSON%20STREET,%20NSW,%202204) returns 5 results in NSW, it looks like [this one is what you're looking for?](http://pelias.github.io/compare/#/v1/place%3Fids=openaddresses:address:au/countrywide:8d54f9feb825a3d2).

What's happening here is that we use the [whosonfirst](https://whosonfirst.org/) gazeteer of places to provide a consistent administrative hierarchy with stable IDs.

It's a known issue in Australia that the data provided in OA has superior locality names than what we're getting from whosonfirst.

There are a bunch of issues already open for this and also some work has gone into resolving the issue, but I expect it won't be fully resolved until the new year.

links: https://github.com/pelias/openaddresses/pull/402

**Comment by missinglink** [comment] 2018-10-29 20:16
For now, you may find you get better results by completely omitting the locality name.

> When I say 'locality', I mean 'city', 'town', 'village', 'hamlet', etc etc etc

**Comment by missinglink** [comment] 2018-10-29 20:19
This is the mechanism we will use to fix the issue https://github.com/pelias/wof-admin-lookup/pull/232

In other countries, we can use the postcode as a hint for the correct locality, but in Australia, it isn't as clear-cut, so we will need to generate some data extracts which allow us to quickly establish the correct locality name in WOF which corresponds to the one listed in the OA CSV file.

**Comment by NickStallman** [comment] 2018-10-29 20:59
Ahh so it's not that it wasn't indexed properly, but rather PIP placed it in Dulwich Hill instead.
That explains it.

Omitting the locality name isn't viable I think due to there being too many streets with the same name in the same state/area.
I think we'll settle for getting exact results with localities, and miss a few from time to time until the issue is resolved.

Thanks I'll close this watch the linked issues.

**Comment by orangejulius** [comment] 2018-10-29 21:01
Another strategy we've had success with is omitting the locality but including either a postcode or county (if you have something like a US county in Australia). The issue is primarily with localities, so other administrative areas can still be used.

**Comment by NickStallman** [comment] 2018-10-29 22:38
We do have LGA's (local government areas or council areas) however they are never used when formatting addresses. I believe this is what is in the county field for Australia in wof.
Unfortunately the data sources that I'm geocoding don't have that information to filter by.

The postalcode appears to get ignored in this specific instance.
https://pelias.github.io/compare/#/v1/search%3Ftext=22%20HENSON%20STREET,%202204,%20NSW
The correct match is there with the matching 2204 postcode but it's below a result in postcode 2216.

**Comment by NickStallman** [comment] 2018-10-31 23:36
@missinglink just on this issue, I've got a second example "11 Classic Court, West Lakes, SA, Australia".
Exact same issue, pip-service is giving Tennyson for the locality instead of West Lakes.

The interesting thing is your https://pip.synergy.io/#18/-34.88751/138.49286 gives the correct results (although not for OSM, not sure what's going there). WOF has the exact right locality with your pip.

I've also checked the source WOF polygons and I don't see any specific issue with them.
https://spelunker.whosonfirst.org/id/101936667/
11 Classic Court isn't anywhere near the WOF polygon, it's even outside the bounding box.

Could this issue actually be due to bad matching rather than bad WOF data?

**Comment by missinglink** [comment] 2018-11-01 09:48
Hey @NickStallman

> housekeeping: it's generally better to open new issues instead of re-opening old ones if they don't match the original title.
> this helps us keep issues succinct and for future searchers to find the issue in a search engine, next to the solution.
> but this time it's fine, I can answer here :)

There are a few reasons this might be happening, but it's most likely because my `pip.synergy.io` domain is not running the official Pelias PIP service, it's running an experimental sqlite+spatialite PIP service I built for R&D purposes.

The guts of the two systems are very different but in terms of functionality, the two systems differ in only three major ways.

- The Pelias PIP service reduces latency by only querying for the lowest matching layer and then using the parent hierarchy included in each document to enumerate the list of parents. Conversely the `pip.synergy.io` system searched on all layers.
- The `pip.synergy.io` buffers point geometries by a set radius (converts them to circles), the Pelias pip service does not.
- The `pip.synergy.io` server provides an optional 'GROUP' function, under-the-hood this is a SQL `GROUP BY` condition, in the case where it finds two records at the same level from the same source then it will only show the one whose centroid is closest to the target point.

The demo at `pip.synergy.io` has some debugging checkboxes in the top right corner which let you inspect the buffered polygons (they are circular but appear as ovals due to the projection) and also enable or disable the grouping.

The othe rmajor difference between the systems will be the age of the data, I last rebuilt the `pip.synergy.io` one a couple months ago and the Pelias one is as old as your last build, or the age of the sqlite databases if you're using our docker setup, which in turn uses the WOF sqlite databases from their distributions.

I would suggest you test out your query using the Pelias PIP service which usually runs on port `4200`, the [docs are here](https://github.com/pelias/pip-service).

Let me know the results of that, I suspect your specific issue is either:
- The data is old/new/changes
- The hierarchy is incorrect (ie. it matches a lower level such as `neighbourhood` which has the wrong `locality`)

Let me know how you get on.

**Comment by NickStallman** [comment] 2018-11-01 17:43
@missinglink yeah I did check with my own pip-service when I was investigating further and pip-service said the locality WOF id for 138.49286/-34.88751 is 101936667.
That's when I noticed in the Spelunker that the WOF polygon doesn't go near those coordinates at all.

I tried it out with your test pip service on a whim, but I mentioned it because your pip gets the right answer.

I've just done some more digging through the code and yeah the commonality does appear to be the 'neighbourhood'. I'm not sure what that actually means (neighbourhoods aren't things that exist in Australia) but WOF has them larger than the locality so it's less specific than locality not more specific.

I might have a fast solution. It should be possible to enforce a strict hierarchy so that if a match is found, but the next layer up has a smaller bounding box then redo the query with the misbehaving layer removed. A proper polygon check would be needed to be strictly accurate, but the pip-service already has the bounding boxes available so it can do that as an extremely fast check to limit any performance impact.

If that's done then the Australia issue should vanish immediately, without breaking any countries where neighbourhoods are used more specifically than localities. If you can't see any issues with that solution that I've missed then I can throw some code together to test out if it would work and measure any slight performance hit it would cause.

**Comment by NickStallman** [comment] 2018-11-01 21:42
Actually it would be easier to run a script to output a list of invalid heirachy nodes and then just not load them when pip-service starts. Zero runtime speed penalty in that case.

I'm still interested to hear what you think about that solution - there are probably tons of things I haven't considered.

**Comment by orangejulius** [comment] 2018-11-01 21:50
We've been considering a change to make the neighbourhood layer not authoritative when it comes to the rest of the hierarchy. Just ensuring we always check the `locality` layer too should help, and won't impact performance _too_ much.

**Comment by orangejulius** [comment] 2019-03-19 18:34
It looks like the work we did in https://github.com/pelias/wof-admin-lookup/pull/246 to fix https://github.com/pelias/wof-admin-lookup/issues/242 has taken care of this issue.

I now get a single correct match for the following query:

[/v1/search?text=22 HENSON STREET, MARRICKVILLE ,NSW,2204](https://pelias.github.io/compare/#/v1/search%3Ftext=22%20HENSON%20STREET,%20MARRICKVILLE%20,NSW,2204)
```
    1) 22 Henson Street, Marrickville, NSW, Australia
```

**Closed by orangejulius** 2019-03-19 18:34 UTC
