### ISSUE TITLE
left in the dust by nominatim

### ISSUE THREAD

**Issue by jeremy-rutman** [pelias/pelias#760] opened 2018-11-29 10:16 UTC
Hey team! 

I was using your awesome geocoding engine when I noticed something interesting.
Let me tell you more about it.

---
#### Here's what I did :innocent:

[pelias search for 219 park hill](http://pelias.github.io/compare/#/v1/search%3Ftext=219%20park%20hill%20dr.,%20san%20antonio,%20tx)

[osm search for 219 park hill](https://www.openstreetmap.org/search?query=219%20park%20hill%20dr.%20san%20antonio%2C%20tx)

[pelias search MIDLAND, MI, 48642, US](http://pelias.github.io/compare/#/v1/search%3Ftext=MIDLAND,%20MI,%2048642,%20US)

[osm search MIDLAND, MI, 48642, US ](https://www.openstreetmap.org/search?query=midland%20%2C%20MI%20%2C%20USA%2048642)

[pelias search 9635 ARLISSON DR, SACRAMENTO, CA, 95827, US ](http://pelias.github.io/compare/#/v1/search%3Ftext=9635%20ARLISSON%20DR,%20SACRAMENTO,%20CA,%2095827,%20US)

[osm search 9635 ARLISSON DR, SACRAMENTO, CA, 95827, US ](https://www.openstreetmap.org/search?query=9635%20ARLISSON%20DR%2C%20SACRAMENTO%2C%20CA%2C%2095827%2C%20US#map=17/38.55765/-121.33729&layers=N)

---
#### Here's what I got :scream_cat:

for san antonio search - general ( county level) results from pelias vs. specific (house level) results from osm (nominatim)

for midland search -  midland texas returned as first result from pelias - zip  ignored in all results. if anything the texas result should be returned after the (correct) michigan result

sacramento search - like san antonio search, pelias doesnt find street, osm does

---
#### Here's what I was expecting :sparkles:
same level of detail from pelias as from osm, given that pelias incorporates osm . 
full use of parsed info inc. zip , state to sort  candidates

---
#### Here's what I think could be improved :trophy:
the libpostal parse for san antonio  was correct.  The osm address apparently is coming from nominatim so  that is doing a better job in this case - maybe it would make sense to use nominatim code in pelias?
same story for midland search.

**Comment by orangejulius** [comment] 2019-01-28 17:51
Hey @jeremy-rutman,
These are most likely examples of the [postal cities problem](https://github.com/pelias/pelias/issues/396).

Pelias has a very powerful understanding of the relationship between say, addresses or streets, and cities. However it's a little bit too strict and not flexible enough in some cases. We have some plans to address that in the future and should be able to solve most of these cases (especially in the US).

In the meantime, a workaround that is pretty effective is to omit the city name from your search queries. If you have a county, you can use that to avoid incorrect matches in some cases.

Since this is pretty well documented I'll close it as a duplicate of https://github.com/pelias/pelias/issues/396, but we'll definitely use these examples as further test cases for any future improvements.

**Closed by orangejulius** 2019-01-28 17:51 UTC
