### ISSUE TITLE
Autocomplete weirdness with plural name

### ISSUE THREAD

**Issue by migurski** [pelias/pelias#212] opened 2016-01-05 22:28 UTC
Seeing a strange auto-complete results [on this November blog post](https://mapzen.com/blog/find-your-community). This works:

<img width="420" alt="singular" src="https://cloud.githubusercontent.com/assets/58730/12129435/7d2bc02a-b3b8-11e5-9dae-cddc9680fafb.png">

…but this is weird:

<img width="418" alt="plural" src="https://cloud.githubusercontent.com/assets/58730/12129445/9070cb80-b3b8-11e5-8364-907c03e869a8.png">

**Comment by riordan** [comment] 2016-01-05 22:33
Pretty crazybanannapants, right?

Not just plurals (see #211) also not all plurals (works great on "truth or consequences").

Still digging into the causes/triggers of this one.

**Comment by riordan** [comment] 2016-01-05 22:53
I'm going to close this one as a dupe since we're tracking it on #211.

**Closed by riordan** 2016-01-05 22:53 UTC
Labels: autocomplete, bug, duplicate
