### ISSUE TITLE
Diacriticals expanded into two characters in query don't work

### ISSUE THREAD

**Issue by dianashk** [pelias/pelias#319] opened 2016-04-21 13:19 UTC
Words with umlauts such as Malmö that are stripped of diacriticals by using two characters (so this example would become Malmoe), are common in the citysearch test cases and we don't handle them well at all.

First reported in pelias/fuzzy-tests#31

**Comment by orangejulius** [comment] 2016-07-02 21:59
Looks like this is also a duplicate of https://github.com/pelias/schema/issues/74

**Comment by trescube** [comment] 2016-07-20 16:13
Bring this up with Al.

**Comment by trescube** [comment] 2016-07-20 16:18
When libpostal corrects Malmö->Malmoe, we won't find it because our data indexes as Malmo.  

Alternatively, pelias could flatten diacriticals before sending to libpostal.

**Comment by trescube** [comment] 2016-11-24 04:04
Fixed in pelias/text-analyzer#18

**Closed by trescube** 2016-11-24 04:04 UTC
Labels: Q4-2016, question
