### ISSUE TITLE
Search against all names provided for a record

### ISSUE THREAD

**Issue by riordan** [pelias/pelias#148] opened 2015-10-13 15:38 UTC
When searching the index, take into account not only the default name for a record, but all other alt-names provided. This will help with internationalization. A user should be able to search for the Statue of Liberty or New York in any language and get back the same records.

**Comment by dianashk** [comment] 2016-07-15 20:35
Closing as a duplicate of pelias/pelias#194

**Closed by dianashk** 2016-07-15 20:35 UTC
Labels: data, epic, processed, wof-related
