### ISSUE TITLE
Structured search: consider if county should be locality/localadmin equivalent

### ISSUE THREAD

**Issue by rmglennon** [pelias/pelias#565] opened 2017-05-02 21:10 UTC
This came in through email support.

The underlying issue is that structured search considers the WoF locality and localadmin to be interchangeable, but county is not currently being evaluated with this group. Determine whether county, especially outside the US, should be considered equivalent here.

The full relationship mapping: https://mapzen.com/documentation/search/structured-geocoding/#whos-on-first-layer-mappings-reference   

The original email for verification and acceptance tests is below.

-----

i'm evaluation the forward geocoder with the structured geocoding API.
Here is my example location:

Bichlachweg 83, 6370 Kitzbühel, Austria which should result in:

- 47.469113
- 12.376353

*Here is the problem:*

When i try to search for this location which locality = Kitzbühel
then the search engine will not find a confident result.

[/v1/search/structured?address=Bichlachweg 83&locality=Kitzbühel&country=at&size=5&lang=de](https://search.mapzen.com/v1/search/structured?address=Bichlachweg%2083&locality=Kitzbühel&country=at&size=5&api_key=xxx&lang=de)

Best result is
- "match_type": "fallback",
- confidence": 0.6

which is not the expected result.

The correct result is only found for the combination of parameters:
- address = Bichlachweg 83
- *county* = Kitzbühel
- country = AT

[/v1/search/structured?address=Bichlachweg 
83&county=Kitzbühel&country=at&size=5&lang=de](https://search.mapzen.com/v1/search/structured?address=Bichlachweg%2083&county=Kitzbühel&country=at&size=5&api_key=xxx&lang=de)

When i try to combine both parameters in to one request with:

[/v1/search/structured?address=Bichlachweg
83&county=Kitzbühel&locality=Kitzbühel&country=at&size=5&lang=de](https://search.mapzen.com/v1/search/structured?address=Bichlachweg%2083&county=Kitzbühel&locality=Kitzbühel&country=at&size=5&api_key=xxx&lang=de)

then the result is also a fallback.

Therefore county is important to find this address, however it can't be
combined with the locality(city) parameter.

**Comment by dianashk** [comment] 2017-05-16 15:17
This is caused by the address being queried for falling just outside the polygon WOF has listed for the locality 

[county](https://whosonfirst.mapzen.com/spelunker/id/102049763/#9/47.4485/12.3074)
[locality](https://whosonfirst.mapzen.com/spelunker/id/101787927/#13/47.4685/12.3754)

The query fails even when running regular search (unstructured) as can be seen [here](http://pelias.github.io/compare/#/v1/search%3Ftext=Bichlachweg%2083,%20Kitzb%C3%BChel,%20at)

Changing the [structured query to specify county](http://pelias.github.io/compare/#/v1/search/structured%3Faddress=Bichlachweg%2083&county=Kitzb%C3%BChel&country=at&size=5&lang=de) works as expected.

**Comment by dianashk** [comment] 2017-07-27 15:38
Check again if it's still not working after latest placeholder integration.

**Comment by dianashk** [comment] 2017-10-11 21:53
This seems to be fixed now!

<img width="976" alt="screen shot 2017-10-11 at 5 48 51 pm" src="https://user-images.githubusercontent.com/5446511/31468720-fe590086-aeac-11e7-83b8-2d3ca26e1fe3.png">

**Closed** 2017-10-16 16:31 UTC
Labels: on-deck
