### ISSUE TITLE
Will every reverse geocoding response will have postal code?

### ISSUE THREAD

**Issue by antopaul** [pelias/pelias#856] opened 2020-03-30 13:55 UTC
Hey team! 

Will Pelias return postal code for every reverse geocoding request? At least for USA? If possible what are the data sources to be imported and what services should be running? 

I plan to run Pelias instance locally for both address search and reverse GC.

Our application requires to get postal code for every reverse GC request. Currently we use HereMaps USA PC Boundary for reverse GC.

Regards,
Anto

**Comment by missinglink** [comment] 2020-03-30 13:59
We only return zip codes in the USA when they are provided by the source dataset, so OpenStreetMap or OpenAddresses.
Many geocoders return the [ZCTA Areas](https://en.wikipedia.org/wiki/ZIP_Code_Tabulation_Area) in lieu of actual ZIP values, we currently don't (although we're considering doing so in the future).

**Comment by missinglink** [comment] 2020-03-30 14:00
There is a broader discussion about whether we provide algorithmically computes postalcodes (which are inherently imperfect) or not, maybe we have a new property called `maybe_postalcode` ;)

**Comment by missinglink** [comment] 2020-03-30 14:03
so while we don't support this right now, looking at our roadmap this functionality will be available this year in Pelias.
here's an example of the upcoming functionality https://spatial.demo.geocode.earth/explore/pip#5/38.561590/-85.387974 from our demos, you'll see the `USCENSUS` values for the `ZCTA` on the right side.

Do they more closely correspond to the values you're seeing in HERE?

**Comment by antopaul** [comment] 2020-03-30 15:12
This is an exact match with what I get from HERE. It will be great if this can contain State code as well then I can avoid look up of State code from another table.

**Comment by missinglink** [comment] 2020-03-30 17:29
I'm not sure what you're referring to when you say 'this', could you provide an example?

**Comment by antopaul** [comment] 2020-03-30 18:01
For the point used in demo link(-85.387974, 38.561590) returns below result when queried against HERE database.
'TRIMBLE', 'KY', '21223', '40006' - Format - county, state,  stfips || ctyfips, postcode.

Demo page lists multiple data items type as "administrative". It will be good to name those columns with distinct names.

**Comment by missinglink** [comment] 2020-03-30 18:21
Agh ok, you can drag that map around BTW ;)
We currently only use the `WOF` values which all have distinct names, these map 1:1 to what you see in the Pelias output geojson.

**Comment by orangejulius** [comment] 2020-08-27 17:20
Hi folks, we've got many issues open regarding postalcodes and when/how to compute them if they aren't present in underlying address data.

I'm going to close this one as a dupe of https://github.com/pelias/pelias/issues/111, since adding postal codes to admin lookup is likely how we'd ensure reverse geocoding requests include them.

**Closed by orangejulius** 2020-08-27 17:20 UTC
