### ISSUE TITLE
Fix capitalization in street names

### ISSUE THREAD

**Issue by dianashk** [pelias/pelias#287] opened 2016-03-19 16:35 UTC
OpenAddresses is no longer normalizing the data to correct for all-caps names. This is causing our results to look messy. Let's figure out a way to fix these at index time. 

Would be interesting to talk to Al B. about a new-age `AI` solution to this age-old problem.

**Comment by orangejulius** [comment] 2016-06-01 18:00
Duplicate of pelias/openaddresses#95

**Closed by orangejulius** 2016-06-01 18:00 UTC
