### ISSUE TITLE
Pelias explain/debug mode

### ISSUE THREAD

**Issue by orangejulius** [pelias/pelias#207] opened 2016-01-05 18:25 UTC
Pelias is a complex system, and we often have queries that for whatever reason don't work how we expect. It takes a lot of time and effort, not to mention permissions, to fully dig into an individual query. We need to wrap all the sources of information we could want into a single, publicly facing endpoint.

This would include, at least:
- Full JSON output of the query as would normally be returned by the API
- Full text of the query sent to Elasticsearch
- Full output of Elasticsearch's explain of the query

Each of these bits of data should then also be available in an easy to digest format (for example using @missinglink's cool tool for condensing/prettifying Elasticsearch explain output

**Comment by riordan** [comment] 2016-01-05 18:32
Related: pelias/api#371

**Comment by dianashk** [comment] 2017-07-24 20:34
duplicate of https://github.com/pelias/api/issues/681

**Comment by dianashk** [comment] 2017-07-24 20:41
@tigerlily-he is going to tackle this long-desired feature as her final project! 🚀

**Comment by dianashk** [comment] 2017-07-24 21:18
# Feature Specification

## Usage
- Pelias API should allow a new `debug=true` parameter that would be accepted for any of the existing endpoints
   - e.g. `/v1/search?text=foo&debug=true`
- This feature should be configurable via `pelias-config` upon startup of the API with at least the following options:
   - enable/disable

## Functionality
We have more and more moving parts managed by our API service. Debug mode should provide insight into the communication with each of those components and the decisions made within the API as a result of each interaction.

### Result format
- When the `debug=true` parameter is specified in the query, any valid response from the Pelias API in the form of `geojson` must have a new `debug_data` property.
- `debug_data` should be an array depicting the stack of events that took place during the processing of the query, where each item in the array contains all the relevant information about that type of activity. See list of event types for reference.

```javascript
{
  debug_data: [ {},{} ],
  geocoding: {},
  type: "FeatureCollection",
  features: [],
  bbox: []
}
```

### Event Types

#### microservice communication
Any interaction with an external service, such as Elasticsearch, placeholder, interpolation, pip, etc.

- URL path and parameters (minus the internal base URL) used to query the service
- round-trip time of request to service
- full response from service

#### predicate decision
Predicates are used for almost every middleware and it is important to trace what decisions were made in each one and in relation to which middleware.

- name of middleware in question
- checks that were considered as part of the decision
- outcome of decision

#### sanitizer
Sanitizers manipulate the `req` object and compile lists of errors and warning based on the query parameters.

- req object (or relevant subset) before middleware was called
- req object (or relevant subset) after middleware was called

#### middleware
Each middleware manipulates the `req` and `res` objects.

- res object before middleware was called
- res object after middleware was called

#### error
There is error middleware which is intended to catch errors that fall through to it.

- Error status code
- Error message
- Full error object that was passed along with the error
- Total time of request processing from receipt to response

#### success

- Success status code
- Total time of request processing from receipt to response

-----

That's all I've come up with so far. It is entirely up for discussion so please provide feedback here. What did you always want to know about our queries but were afraid to ask?

**Comment by missinglink** [comment] 2017-07-25 14:56
we could remove the `?debug=` param in the fastly config to ensure it is never enabled for the `search.mapzen.com` hosted service.

**Comment by tigerlily-he** [comment] 2017-08-07 14:35
Before this feature gets deployed to production: 
- [ ]  Change Fastly Configuration settings to remove `debug=` parameter from the query. Flag can only be accessed while on VPN?

**Comment by missinglink** [comment] 2017-08-08 12:26
fastly docs: https://docs.fastly.com/guides/vcl/query-string-manipulation-vcl-features

cc/ our VCL master @sleepylemur

hey Evan, could you please explain the easiest was to ensure that the input parameter named `debug` is always removed from requests in the VCL before being sent to the backend.

we don't want external users in our prod environment to be able to set `?debug=true` due to the performance hit associated with making those requests.

thanks!

**Comment by sleepylemur** [comment] 2017-08-08 15:49
I believe @rmarianski and @orangejulius know vcl better than me, but my understanding is that you need to do a regex replace on the url. Probably something along the lines of `/\?debug=[^&]+&?/?/g` and `/&debug=[^&]+//g`

**Comment by rmarianski** [comment] 2017-08-08 15:57
Regex replace should work, but it might be worth looking into the docs that @missinglink linked to for a more explicit way to do it if that's clearer.

Taking a step back, is this an option that you want to have available in production at all, even internally? If not, you can just configure it off for the service itself in production.

**Comment by orangejulius** [comment] 2017-08-08 16:42
We do want the feature enabled for production, but only accessible when we are on VPN connecting directly to the internal load balancer.

I believe the [query string manipulation tools](https://docs.fastly.com/guides/vcl/query-string-manipulation-vcl-features) that VCL has should do the job nicely.

**Comment by sleepylemur** [comment] 2017-08-08 16:43
oh word, querystring.filter or querystring.filter_except look good

**Comment by dianashk** [comment] 2017-09-18 20:41
This has been released! :tada: Thanks @tigerlily-he! :heart:

**Closed by dianashk** 2017-09-18 20:41 UTC
Labels: in progress, nyresolution-2016, Q3-2017
