### ISSUE TITLE
Deduplication of results with abbreviation (Ave vs Avenue)

### ISSUE THREAD

**Issue by rmglennon** [pelias/pelias#688] opened 2017-11-22 18:03 UTC
This came in through support (see Desk 1293)

#### Here's what I did :innocent:

The user was doing an autocomplete, and noticed essentially duplicated results.

http://pelias.github.io/compare/#/v1/autocomplete%3Flayers=venue,address&boundary.rect.min_lat=37.08228960001098&boundary.rect.min_lon=-123.42283261328123&boundary.rect.max_lat=37.831201327677896&boundary.rect.max_lon=-120.96738827734373&focus.point.lat=37.45674546384444&focus.point.lon=-122.19511044531248&text=1684%20k

---
#### Here's what I got :scream_cat:
Many results are duplicated between OSM and OA sources, differing only in the street abbreviation.

1684 Kentfield Ave, Redwood City, CA, USA
 1684 Kentfield Avenue, Redwood City, CA, USA
 1684 Mc Kinley St, San Mateo, CA, USA
 1684 Kitchener Dr, Sunnyvale, CA, USA
 1684 Kitchener Drive, Sunnyvale, CA, USA
 1684 Kintyre Way, Sunnyvale, CA, USA
 1684 Kintyre Wy, Sunnyvale, CA, USA
 1684 Kains Ave, San Bruno, CA, USA
 1684 Kevin Dr, San Jose, CA, USA

Here is the JSON for the first two results in Redwood City, CA:

"properties": {
        "id": "us/ca/san_mateo:180305",
        "gid": "openaddresses:address:us/ca/san_mateo:180305",
        "layer": "address",
        "source": "openaddresses",
        "source_id": "us/ca/san_mateo:180305",
        "name": "1684 Kentfield Ave",
        "housenumber": "1684",
        "street": "Kentfield Ave",
        "distance": 2.856,
        "accuracy": "point",
        "country": "United States",
        "country_gid": "whosonfirst:country:85633793",
        "country_a": "USA",
        "region": "California",
        "region_gid": "whosonfirst:region:85688637",
        "region_a": "CA",
        "county": "San Mateo County",
        "county_gid": "whosonfirst:county:102085387",
        "locality": "Redwood City",
        "locality_gid": "whosonfirst:locality:85922447",
        "neighbourhood": "Kentfield Commons",
        "neighbourhood_gid": "whosonfirst:neighbourhood:420552363",
        "label": "1684 Kentfield Ave, Redwood City, CA, USA"
      }

     "properties": {
        "id": "way:240581298",
        "gid": "openstreetmap:address:way:240581298",
        "layer": "address",
        "source": "openstreetmap",
        "source_id": "way:240581298",
        "name": "1684 Kentfield Avenue",
        "housenumber": "1684",
        "street": "Kentfield Avenue",
        "distance": 2.862,
        "accuracy": "point",
        "country": "United States",
        "country_gid": "whosonfirst:country:85633793",
        "country_a": "USA",
        "region": "California",
        "region_gid": "whosonfirst:region:85688637",
        "region_a": "CA",
        "county": "San Mateo County",
        "county_gid": "whosonfirst:county:102085387",
        "locality": "Redwood City",
        "locality_gid": "whosonfirst:locality:85922447",
        "neighbourhood": "Kentfield Commons",
        "neighbourhood_gid": "whosonfirst:neighbourhood:420552363",
        "continent": "North America",
        "continent_gid": "whosonfirst:continent:102191575",
        "label": "1684 Kentfield Avenue, Redwood City, CA, USA"
      }

---
#### Here's what I was expecting :sparkles:
Only one result being returned.

---
#### Here's what I think could be improved :trophy:
Better deduplication of results between OA and OSM when OSM has a complete address.

**Comment by orangejulius** [comment] 2019-02-14 04:42
Closing as a dupe of https://github.com/pelias/api/issues/588

**Closed by orangejulius** 2019-02-14 04:42 UTC
