### ISSUE TITLE
Search for Athens (a WoF megacity) puts it lower in the result list

### ISSUE THREAD

**Issue by rmglennon** [pelias/pelias#625] opened 2017-08-22 20:51 UTC
#### Here's what I did :innocent:
This came in through support (see Desk 888).

Search for Athens, with or without additional parameters for data sources, and so on. Here's the user's query:

https://mapzen.com/search/explorer/?query=search&text=athens&sources=wof&layers=country%2Clocality

---
#### Here's what I got :scream_cat:
 1. Athens-Clarke County, GA, USA
 2. Athens, Greece
and then a bunch of other US results
---
#### Here's what I was expecting :sparkles:
Without a focus point, boost the larger city higher, especially because this record has population data and is a "megacity" in WoF.

https://whosonfirst.mapzen.com/spelunker/id/101752329/

---
#### Here's what I think could be improved :trophy:
Consider larger cities higher.

**Comment by dianashk** [comment] 2017-08-22 21:01
It looks like libpostal doesn't deem this to be an admin only query so we fallback to addressit and old-style ES queries.

**Comment by orangejulius** [comment] 2017-09-18 16:32
This could be caused by an incorrect `label` field in the [Athens locality record](https://whosonfirst.mapzen.com/spelunker/id/85936177/) (it says Athens-Clarke County when it should just say Athens). We'll have this fixed soon and see if it sorts itself out.

**Comment by orangejulius** [comment] 2017-10-02 14:22
This looks fixed now!
https://mapzen.com/search/explorer/?query=search&text=athens%2C%20greece&sources=wof&layers=country%2Clocality
![image](https://user-images.githubusercontent.com/111716/31082000-a4c572f0-a75b-11e7-958c-8be76a8b7a9f.png)

**Closed by orangejulius** 2017-10-02 14:22 UTC
Labels: in progress, on-deck
