### ISSUE TITLE
build Pelias docker for non listed countries

### ISSUE THREAD

**Issue by december1990** [pelias/pelias#923] opened 2022-01-19 16:31 UTC
I built the Pelias docker for portland-metro project and it worked very well, but now I wanna know how should I build the project for other countries that aren't listed in the projects folder.

 thanks in advance

**Comment by missinglink** [comment] 2022-01-19 19:01
closing as duplicate of https://github.com/pelias/docker/issues/280

**Closed by missinglink** 2022-01-19 19:01 UTC
Labels: bug
