### ISSUE TITLE
autocomplete: search string not found but expected.

### ISSUE THREAD

**Issue by oliverbienert** [pelias/pelias#488] opened 2016-12-20 22:05 UTC
Hey team! 

I was using your awesome geocoding engine when I noticed something interesting.
Let me tell you more about it.

---
#### Here's what I did :innocent:

(I removed api_key argument intentionally)
This returns zero results:
[karl-liebknecht-str](https://search.mapzen.com/v1/autocomplete?text=karl-liebknecht-str)

But if remove the 'r' from the end of the string, I get the expected result:
[karl-liebknecht-st](https://search.mapzen.com/v1/autocomplete?text=karl-liebknecht-st)

Interesting: Using `search` instead of `autocomplete` yields exactly the same results.

However, both queries should return roughly the same results, that is, a number of features labeled 'Karl-Liebknecht-Straße...'

I'd like to know what's going on?  I guess it's an elastic search issue, somehow?

For the following sub strings the result is empty:
*str
*stra
*straß
Then again, the exact search term (case-insensitive) 'karl-liebknecht-straße' returns the expected result.

Is there a possibility to use wild cards?
Or is this a language issue? 
Is this a stemming issue?
How can I make sure that german stemming is used?

Oliver

**Comment by orangejulius** [comment] 2016-12-20 22:11
Hey @oliverbienert,
Thanks for reporting this. The answer is that we only store [the first 18 characters of every word](https://github.com/pelias/schema/blob/master/settings.js#L171), but we should store more (obviously). We track this issue in https://github.com/pelias/schema/issues/126.

An interesting side effect is that a query for [karl liebknecht str](http://pelias.github.io/compare/#/v1/autocomplete%3Ftext=karl%20liebknecht%20str) will return results, because we store hyphenated street names both as one big long word, and as individual words, none of which by themselves violate the 18 character maximum in this case.

**Comment by oliverbienert** [comment] 2016-12-20 22:25
Hej, thank you for quick response!
I see that this [issue](pelias/schema#126) is still open since April, will this be solved any time soon?
Or is there a way to modify schema settings without forking?
Maybe by having my own settings and merging as in pelias-config?
I've never worked with elastic search until now.

**Comment by oliverbienert** [comment] 2016-12-21 10:36
Hi @orangejulius,

I think, we'll resolve the issue for now by increasing the `max_gram` parameter to 30 in our local instance as suggested in pelias/schema#126.

Thank you for the hint.

**Comment by orangejulius** [comment] 2016-12-21 15:52
Yes, let us know how it goes. There's nothing really stopping us from making the change, as I think there's not much work involved. It just hasn't been a huge priority.

**Comment by missinglink** [comment] 2017-05-30 13:50
I expect this issue to have been resolved in https://github.com/pelias/schema/pull/224, at time of writing that code hasn't made it to production, leaving this ticket open until I can confirm it's resolved.

**Comment by orangejulius** [comment] 2017-11-14 19:17
Hi all!
Its been a while since we've updated anything here but this looks to be working great after we increased the max ngram size.

http://pelias.github.io/compare/#/v1/autocomplete%3Ftext=karl-liebknecht-str
![image](https://user-images.githubusercontent.com/111716/32799691-799e8b04-c946-11e7-936b-35cfd03b6029.png)

We'll consider this fixed for now. Someday I'm sure we'll find an even longer (probably German) streetname, but until then, happy searching :)

**Closed by orangejulius** 2017-11-14 19:17 UTC
