### ISSUE TITLE
Import admin hierarchy from osm data [Question]

### ISSUE THREAD

**Issue by sweco-semtne** [pelias/pelias#542] opened 2017-04-11 13:49 UTC
Hi,
I've got a question on extension points for using more info from openstreetmap. 
I've got address data (no POIs) in OSM-format with addr:postcode, addr:number, addr:street, addr:country, addr:county, addr:province etc which I would like to use instead of an admin lookup from WOF. 

Should I customize the openstreetmap to do my own admin lookup or can I add the parent document somehow and just disable WOF lookup?

**Comment by orangejulius** [comment] 2017-04-12 16:44
Hey @sweco-semtne,
There is no support for doing admin lookup from OSM right now , but you could probably modify the importer code to get close to what you want.

You'll find that OSM admin data does not always fit into the same model that pelias uses for admin data (which is based on the [whosonfirst hierarchy](https://github.com/whosonfirst/whosonfirst-placetypes). This is why, in the past, when we've [talked about adding support for admin lookup from OSM](https://github.com/pelias/pelias/issues/389), we've eventually decided not to build in support for it out of the box. However, don't let that discourage you from trying to find a solution that works for just your case! And if you have any success (or not), please let us know how it goes.

If you take a look at [pelias/model](https://github.com/pelias/model) you'll see the interface for setting properties on documents in Pelias. In particular take a look at the `addParent()` method, which is how you specify that a document is in a particular city, county, etc.

**Comment by sweco-semtne** [comment] 2017-04-12 19:14
Thanks for your quick reply. We don't actually have OSM data but instead we format data as OSM to be able to use it with Pelias.
How hard would it be to create another source modeled after the openstreetmap source?
I'm thinking that the tag_mapper and extract_address could be used with minor modifications. 
If a create another import pipeline will the API automatically pickup the new source and layer?

**Comment by orangejulius** [comment] 2017-04-12 19:23
Oh, if you don't actually have OSM data, you might want to consider formatting your data for the Openaddresses importer (which simply takes a CSV) instead. There is a [pull request](https://github.com/pelias/openaddresses/pull/168) for that repository that adds rudimentary support for using the admin fields in the Openaddresses files instead of WOF.

**Comment by orangejulius** [comment] 2019-07-15 20:45
Closing as duplicate of https://github.com/pelias/pelias/issues/389

**Closed by orangejulius** 2019-07-15 20:45 UTC
