### ISSUE TITLE
Can we return the postcode in /place response?

### ISSUE THREAD

**Issue by msschl** [pelias/pelias#887] opened 2020-08-27 16:50 UTC
It would be nice to have the postcode of a place returned within the place response.

### Suggestion
`/v1/place?ids=openaddresses:address:de/nw/statewide:979bd2e6b8b4685e` should return the appropriate postcode in the `properties` object. If the postcode is unknown do return `"postcode": null` or exclude the property from the response.

**Comment by orangejulius** [comment] 2020-08-27 17:01
Hi @msschl,
Thanks for the report!

The intended functionality is definitely that the `/v1/place` endpoint returns a postalcode the same as any other query. Even after a few minutes of looking I can't figure out why it wouldn't do that.

If you happen to take a look and figure it out, feel free to let us know or open a PR. We'll investigate further as well.

**Comment by orangejulius** [comment] 2020-08-27 17:18
Okay I'm back with good and bad news.

Good news: there's no bug in the `/v1/place` endpoint, it will return postalcode just fine the same as any other endpoint, as intended.

The bad news is the record you've listed as an example does not have a postalcode, and currently Pelias will not return a postalcode for any address or POI record that doesn't come with one.

There are some big discussions over in https://github.com/pelias/pelias/issues/111, https://github.com/pelias/pelias/issues/856, https://github.com/pelias/pelias/issues/777 and probably others about this.

In general, it's not possible to accurately compute a postcode for an address, so we deliberately choose not to have Pelias attempt to do that and risk sending back inaccurate data. Germany is one of the few exceptions where it _is_ possible, and future work will allow us to return better postalcode results in Germany.

For now, keep in mind that queries to the _search_ endpoint will always prefer results with a postalcode, so for example if you search for [Am Nordkanal 18, Willich, Germany](https://pelias.github.io/compare/#/v1/search?text=Am+Nordkanal+18%2C+Willich%2C+Germany) you will get an OpenAddresses record (from another source) that _does_ have a postalcode.

With all that in mind I'm going to mark this as a duplicate of https://github.com/pelias/pelias/issues/111. Let us know if you have any more questions.

**Closed by orangejulius** 2020-08-27 17:18 UTC
Labels: bug

**Comment by msschl** [comment] 2020-08-27 17:52
Thanks @orangejulius for your fast response.

However, your listed example returns the following `properties` from `https://api.geocode.earth`:
```json
"properties": {
	"id": "de/nw/kreis_viersen:8d5a1dbb0e679017",
	"gid": "openaddresses:address:de/nw/kreis_viersen:8d5a1dbb0e679017",
	"layer": "address",
	"source": "openaddresses",
	"source_id": "de/nw/kreis_viersen:8d5a1dbb0e679017",
	"name": "Am Nordkanal 18",
	"housenumber": "18",
	"street": "Am Nordkanal",
	"postalcode": "47877",
	"confidence": 1,
	"match_type": "exact",
	"accuracy": "point",
	"country": "Germany",
	"country_gid": "whosonfirst:country:85633111",
	"country_a": "DEU",
	"region": "North Rhine-Westphalia",
	"region_gid": "whosonfirst:region:85682513",
	"region_a": "NW",
	"macrocounty": "Düsseldorf Government Region",
	"macrocounty_gid": "whosonfirst:macrocounty:404227561",
	"county": "Viersen",
	"county_gid": "whosonfirst:county:102063773",
	"county_a": "VE",
	"localadmin": "Willich",
	"localadmin_gid": "whosonfirst:localadmin:1377689855",
	"locality": "Willich",
	"locality_gid": "whosonfirst:locality:101748687",
	"continent": "Europe",
	"continent_gid": "whosonfirst:continent:102191581",
	"label": "Am Nordkanal 18, Willich, Germany"
}
```

When running this query on our instance it returns an other `gid` and also doesn't provide the postcode:
```json
"properties": {
    "id": "de/nw/statewide:979bd2e6b8b4685e",
    "gid": "openaddresses:address:de/nw/statewide:979bd2e6b8b4685e",
    "layer": "address",
    "source": "openaddresses",
    "source_id": "de/nw/statewide:979bd2e6b8b4685e",
    "name": "Am Nordkanal 18",
    "housenumber": "18",
    "street": "Am Nordkanal",
    "confidence": 1,
    "match_type": "exact",
    "accuracy": "point",
    "country": "Germany",
    "country_gid": "whosonfirst:country:85633111",
    "country_a": "DEU",
    "region": "North Rhine-Westphalia",
    "region_gid": "whosonfirst:region:85682513",
    "region_a": "NW",
    "macrocounty": "Düsseldorf Government Region",
    "macrocounty_gid": "whosonfirst:macrocounty:404227561",
    "county": "Viersen",
    "county_gid": "whosonfirst:county:102063773",
    "county_a": "VE",
    "localadmin": "Willich",
    "localadmin_gid": "whosonfirst:localadmin:1377689855",
    "locality": "Willich",
    "locality_gid": "whosonfirst:locality:101748687",
    "label": "Am Nordkanal 18, Willich, Germany"
}
```

This is our pelias-configmap. Is there a setting we have to set?
```json
{
	"logger": {
		"level": "debug",
		"timestamp": true
	},
	"esclient": {
		"apiVersion": "7.6",
		"hosts": [
			{
				"protocol": "http",
				"host": "elasticsearch-master.elasticsearch.svc.k8s-cluster.company.xyz",
				"port": 9200
			}
		]
	},
	"elasticsearch": {
		"settings": {
			"index": {
				"refresh_interval": "10s",
				"number_of_replicas": "1",
				"number_of_shards": "1"
			}
		}
	},
	"api": {
		"autocomplete": {
			"exclude_address_length": 0
		},
		"indexName": "pelias",
		"exposeInternalDebugTools": true,
		"services": {
			"pip": { "url": "http://pelias-pip.map-services.svc.k8s-cluster.company.xyz" },
			"libpostal": { "url": "http://pelias-libpostal.map-services.svc.k8s-cluster.company.xyz" },
			"placeholder": { "url": "http://pelias-placeholder.map-services.svc.k8s-cluster.company.xyz" },
			"interpolation": { "url": "http://pelias-interpolation.map-services.svc.k8s-cluster.company.xyz" }
		}
	},
	"schema": {
		"indexName": "pelias",
		"typeName": "_doc"
	},
	"imports": {
		"adminLookup": {
			"enabled": true
		},
		"geonames": {
			"datapath": "/data/geonames",
			"countryCode": "DE",
			"sourceURL": "https://download.geonames.org/export/dump/DE.zip"
		},
		"openstreetmap": {
			"download": [
				{ "sourceURL": "http://download.geofabrik.de/europe/germany-latest.osm.pbf" }
			],
			"datapath": "/data/openstreetmap",
			"import": [{
				"filename": "germany-latest.osm.pbf"
			}]
		},
		"openaddresses": {
			"datapath": "/data/openaddresses",
			"files": ["de/hh/statewide.csv", "de/nw/city_of_cologne.csv", "de/nw/city_of_wesel.csv", "de/nw/city_of_wuppertal.csv", "de/nw/statewide.csv", "de/th/statewide.csv"]
		},
		"polyline": {
			"datapath": "/data/polylines",
			"files": [ "extract.0sv" ]
		},
		"whosonfirst": {
			"datapath": "/data/whosonfirst",
			"countryCode": "de"
		}
	}
}
```
