### ISSUE TITLE
Add ability to search for addresses using its parts

### ISSUE THREAD

**Issue by dianashk** [pelias/pelias#417] opened 2016-09-09 13:39 UTC
Implement a way for users to specify an address using the traditional (at least in the USA 🇺🇸) address format: `housenumber + street`, `city`, `state`, `postalcode`.

This new feature should only work on its own and not in combination with the existing `text` parameter. Errors should be returned if both are provided.

Additional filtering should still apply, such `boundary.*` and `sources`. `layers` filter is assumed to default to `address` in this scenario, so if the user provides something other than `address` for the `layers` filter an error should be returned.

**Comment by orangejulius** [comment] 2016-09-09 17:09
Is this a dupe of https://github.com/pelias/pelias/issues/213?

**Comment by dianashk** [comment] 2016-09-19 16:41
Good catch, @orangejulius. Closing the other one since this has more detail. Although it's important to note that @riordan's New Year Resolution is about to get checked off the list! 🎉

**Closed** 2016-12-09 15:24 UTC
Labels: nyresolution-2016
