### ISSUE TITLE
Incorrect directional in this address really throws off search

### ISSUE THREAD

**Issue by rmglennon** [pelias/pelias#586] opened 2017-06-01 03:52 UTC
Hey team! 

I was using your awesome geocoding engine when I noticed something interesting.
Let me tell you more about it.

---
#### Here's what I did :innocent:
A user contacted us about an unrelated search problem and happened to mention this address: [1133 N Rosemont Ave, Pasadena, CA](https://pelias.github.io/compare/#/v1/search?text=1133+N+Rosemont+Ave+Pasadena+CA&debug=1)

---
#### Here's what I got :scream_cat:
I got fall back results for localities.

Pasadena, CA, USA
South Pasadena, CA, USA
East Pasadena, CA, USA
Old Town Pasadena, CA, USA

"query": {
      "text": "1133 N Rosemont Ave Pasadena CA",
      "parsed_text": {
        "number": "1133",
        "street": "n rosemont ave",
        "city": "pasadena",
        "state": "ca"
}

(similar results happen with /structured as well)

---
#### Here's what I was expecting :sparkles:
I looked in some other data sources and believe the N directional is incorrect. If I search for [1133 Rosemont Ave Pasadena CA](https://pelias.github.io/compare/#/v1/search?text=1133+Rosemont+Ave+Pasadena+CA&debug=1), there's an exact match returned.

properties": {
"id": "us/ca/los_angeles:753a217a5639eb09",
"gid": "openaddresses:address:us/ca/los_angeles:753a217a5639eb09",
"layer": "address",
"source": "openaddresses",
"source_id": "us/ca/los_angeles:753a217a5639eb09",
"name": "1133 Rosemont Ave",
"housenumber": "1133",
"street": "Rosemont Ave",
"postalcode": "91103",
"confidence": 1,
"match_type": "exact",
"accuracy": "point",
"country": "United States",
"country_gid": "whosonfirst:country:85633793",
"country_a": "USA",
"region": "California",
"region_gid": "whosonfirst:region:85688637",
"region_a": "CA",
"county": "Los Angeles County",
"county_gid": "whosonfirst:county:102086957",
"locality": "Pasadena",
"locality_gid": "whosonfirst:locality:85923487",
"neighbourhood": "Linda Vista",
"neighbourhood_gid": "whosonfirst:neighbourhood:85830681",
"label": "1133 Rosemont Ave, Pasadena, CA, USA"
}

---
#### Here's what I think could be improved :trophy:
Try to return a result without the directional if everything else matches.

**Comment by orangejulius** [comment] 2020-06-26 17:52
Duplicate of https://github.com/pelias/pelias/issues/740, but a great test case!

**Closed by orangejulius** 2020-06-26 17:52 UTC
