### ISSUE TITLE
Autocomplete zip/post code

### ISSUE THREAD

**Issue by Petah** [pelias/pelias#832] opened 2019-10-29 22:45 UTC
Hi,

Is it possible to autocomplete zip/post codes? I have looked around and there is a few previous issues about this but I am unable to find a clear answer if this is possible, or how to do it.

**Comment by missinglink** [comment] 2019-10-30 10:27
Currently, this is not possible, there is a draft PR which would allow this https://github.com/pelias/schema/pull/379, but it's a complex issue and we're not ready to merge that yet, if you'd like to give it a spin and provide feedback that'd be great!

Closing as a duplicate of https://github.com/pelias/pelias/issues/676 which contains examples

**Closed** 2019-10-30 10:28 UTC

**Comment by Petah** [comment] 2020-03-12 22:18
@missinglink It looks like the PR was merged, does this mean its supported now?

**Comment by missinglink** [comment] 2020-03-13 09:27
I believe that the past restrictions have been lifted so it's now certainly possible:

https://pelias.github.io/compare/#/v1/search?text=90210&debug=0

**Comment by missinglink** [comment] 2020-03-13 09:27
https://pelias.github.io/compare/#/v1/autocomplete?text=90210&debug=0

**Comment by missinglink** [comment] 2020-03-13 09:33
It seems fully specified postalcodes as supported but partially specified codes are not:

https://pelias.github.io/compare/#/v1/autocomplete?boundary.country=us&layers=postalcode&text=9021&debug=0

**Comment by Petah** [comment] 2020-03-16 19:52
@missinglink is there something I need to do to get it to work? I tried re-cloning, downloading, importing (the whos on first and open street maps north america data set) on a new elasticsearch instance but it didn't seem to work for me:

http://myhost:3100/v1/autocomplete?text=90210
```
{
    "geocoding": {
        "version": "0.2",
        "attribution": "http://geo.printicular.com:3100/attribution",
        "query": {
            "text": "90210",
            "parser": "pelias",
            "parsed_text": {
                "subject": "90210",
                "postcode": "90210"
            },
            "size": 10,
            "layers": [
                "venue",
                "street",
                "country",
                "macroregion",
                "region",
                "county",
                "localadmin",
                "locality",
                "borough",
                "neighbourhood",
                "continent",
                "empire",
                "dependency",
                "macrocounty",
                "macrohood",
                "microhood",
                "disputed",
                "postalcode",
                "ocean",
                "marinearea"
            ],
            "private": false,
            "lang": {
                "name": "English",
                "iso6391": "en",
                "iso6393": "eng",
                "defaulted": false
            }
        },
        "warnings": [
            "performance optimization: excluding 'address' layer"
        ],
        "engine": {
            "name": "Pelias",
            "author": "Mapzen",
            "version": "1.0"
        },
        "timestamp": 1584388006769
    },
    "type": "FeatureCollection",
    "features": [
        {
            "type": "Feature",
            "geometry": {
                "type": "Point",
                "coordinates": [
                    -118.117395,
                    34.190749
                ]
            },
            "properties": {
                "id": "node/4357753721",
                "gid": "openstreetmap:venue:node/4357753721",
                "layer": "venue",
                "source": "openstreetmap",
                "source_id": "node/4357753721",
                "name": "Dilan's Home (Beverly Hills 90210)",
                "housenumber": "1605",
                "street": "East Altadena Drive",
                "postalcode": "91001",
                "accuracy": "point",
                "country": "United States",
                "country_gid": "whosonfirst:country:85633793",
                "country_a": "USA",
                "region": "California",
                "region_gid": "whosonfirst:region:85688637",
                "region_a": "CA",
                "locality": "Altadena",
                "locality_gid": "whosonfirst:locality:85928289",
                "continent": "North America",
                "continent_gid": "whosonfirst:continent:102191575",
                "label": "Dilan's Home (Beverly Hills 90210), Altadena, CA, USA"
            }
        },
        {
            "type": "Feature",
            "geometry": {
                "type": "Point",
                "coordinates": [
                    -118.116127,
                    34.190957
                ]
            },
            "properties": {
                "id": "node/4357760206",
                "gid": "openstreetmap:venue:node/4357760206",
                "layer": "venue",
                "source": "openstreetmap",
                "source_id": "node/4357760206",
                "name": "Walsh Home (Beverly Hills 90210)",
                "housenumber": "1675",
                "street": "East Altadena Drive",
                "postalcode": "91001",
                "accuracy": "point",
                "country": "United States",
                "country_gid": "whosonfirst:country:85633793",
                "country_a": "USA",
                "region": "California",
                "region_gid": "whosonfirst:region:85688637",
                "region_a": "CA",
                "locality": "Altadena",
                "locality_gid": "whosonfirst:locality:85928289",
                "continent": "North America",
                "continent_gid": "whosonfirst:continent:102191575",
                "label": "Walsh Home (Beverly Hills 90210), Altadena, CA, USA"
            }
        },
        {
            "type": "Feature",
            "geometry": {
                "type": "Point",
                "coordinates": [
                    -118.321026,
                    33.829695
                ]
            },
            "properties": {
                "id": "node/4357780108",
                "gid": "openstreetmap:venue:node/4357780108",
                "layer": "venue",
                "source": "openstreetmap",
                "source_id": "node/4357780108",
                "name": "Torrance High School (West Beverly High School 90210)",
                "housenumber": "2200",
                "street": "West Carson Street",
                "postalcode": "90501",
                "accuracy": "point",
                "country": "United States",
                "country_gid": "whosonfirst:country:85633793",
                "country_a": "USA",
                "region": "California",
                "region_gid": "whosonfirst:region:85688637",
                "region_a": "CA",
                "locality": "Torrance",
                "locality_gid": "whosonfirst:locality:85923785",
                "continent": "North America",
                "continent_gid": "whosonfirst:continent:102191575",
                "label": "Torrance High School (West Beverly High School 90210), Torrance, CA, USA"
            }
        }
    ],
    "bbox": [
        -118.321026,
        33.829695,
        -118.116127,
        34.190957
    ]
}
```

**Comment by orangejulius** [comment] 2020-03-16 22:20
Unfortunately there will still be some development work required here. We thought the work in https://github.com/pelias/schema/pull/379 would be enough, but the Pelias API does not actually generate appropriate queries to handle partial postal codes currently.

Because of the show, 90210 is a bit of a difficult example (we'll get to it eventually), but here's a simpler example of an American postal code that doesn't work with partial input:

[/v1/autocomplete?boundary.gid=whosonfirst:locality:85922583&text=9410](https://pelias.github.io/compare/#/v1/autocomplete?boundary.gid=whosonfirst%3Alocality%3A85922583&text=9410)

[/v1/autocomplete?boundary.gid=whosonfirst:locality:85922583&text=94105](https://pelias.github.io/compare/#/v1/autocomplete?boundary.gid=whosonfirst%3Alocality%3A85922583&text=94105)

**Comment by Petah** [comment] 2020-03-17 01:15
@orangejulius I understand it doesn't support partial postcodes, but my example/test above I was just trying to use the full postcode.

This is what I get for http://myhost:3100/v1/autocomplete?text=94105

```
{
    "geocoding": {
        "version": "0.2",
        "attribution": "http://myhost:3100/attribution",
        "query": {
            "text": "94105",
            "parser": "pelias",
            "parsed_text": {
                "subject": "94105",
                "postcode": "94105"
            },
            "size": 10,
            "layers": [
                "venue",
                "street",
                "country",
                "macroregion",
                "region",
                "county",
                "localadmin",
                "locality",
                "borough",
                "neighbourhood",
                "continent",
                "empire",
                "dependency",
                "macrocounty",
                "macrohood",
                "microhood",
                "disputed",
                "postalcode",
                "ocean",
                "marinearea"
            ],
            "private": false,
            "lang": {
                "name": "English",
                "iso6391": "en",
                "iso6393": "eng",
                "defaulted": false
            }
        },
        "warnings": [
            "performance optimization: excluding 'address' layer"
        ],
        "engine": {
            "name": "Pelias",
            "author": "Mapzen",
            "version": "1.0"
        },
        "timestamp": 1584407640044
    },
    "type": "FeatureCollection",
    "features": []
}
```

**Comment by Petah** [comment] 2020-03-19 22:11
@missinglink @orangejulius sorry to be a pain, I'm just trying to get this to work. Is there some branch I need to be on to get it working like whats on https://pelias.github.io/

Im on commit 2a2d69194001bc076d2b58c7c316ee5deda10c15 for the schema, did a full clone, install, download, new ES instance. Running on AWS ES 7.4 if that makes a difference.

![pelias github io_compare_](https://user-images.githubusercontent.com/134799/77119481-6c705e00-6a9b-11ea-934e-ad20f59d77a8.png)

**Comment by orangejulius** [comment] 2020-03-19 22:53
Hi @Petah,

Sorry about that, you've fallen victim to a configuration option we should have updated about [2.5 years ago](https://github.com/pelias/config/issues/61).

I've just gone ahead and fixed it, if you update and re-run the whosonfirst importer, you should see postalcodes at least for complete inputs.

That means `pelias compose pull` if you're using a docker based setup, or something like `git pull && npm install` if you're running outside of Docker.

**Comment by Petah** [comment] 2020-04-08 21:39
@orangejulius Hi, sorry still trying to get this working. 

Did a pull, deleted the index, re-created, downloaded whosonfirst, ran the start script but got this error:

```
2020-04-07T20:36:51.620Z - info: [dbclient-whosonfirst]  paused=false, transient=0, current_length=80, indexed=569000, batch_ok=1138, batch_retries=0, failed_records=0, region=4322, country=199, dependency=32, disputed=78, macroregion=25, ocean=7, marinearea=305, continent=8, persec=50, macrocounty=50, county=25615, localadmin=137327, locality=312597, borough=154, macrohood=296, neighbourhood=83904, postalcode=4081
2020-04-07T20:36:57.038Z - info: [whosonfirst] Loading whosonfirst-data-postalcode-ba-latest.csv records from /pelias/data/whosonfirst/meta
2020-04-07T20:36:57.139Z - info: [whosonfirst] Loading whosonfirst-data-postalcode-bd-latest.csv records from /pelias/data/whosonfirst/meta
2020-04-07T20:36:57.888Z - info: [whosonfirst] Loading whosonfirst-data-postalcode-be-latest.csv records from /pelias/data/whosonfirst/meta
2020-04-07T20:36:58.097Z - info: [whosonfirst] Loading whosonfirst-data-postalcode-bg-latest.csv records from /pelias/data/whosonfirst/meta
2020-04-07T20:36:58.468Z - info: [whosonfirst] Loading whosonfirst-data-postalcode-br-latest.csv records from /pelias/data/whosonfirst/meta
2020-04-07T20:37:03.329Z - info: [dbclient-whosonfirst]  paused=false, transient=0, current_length=134, indexed=569000, batch_ok=1138, batch_retries=0, failed_records=0, region=4322, country=199, dependency=32, disputed=78, macroregion=25, ocean=7, marinearea=305, continent=8, persec=0, macrocounty=50, county=25615, localadmin=137327, locality=312597, borough=154, macrohood=296, neighbourhood=83904, postalcode=4081
2020-04-07T20:37:08.439Z - info: [whosonfirst] Loading whosonfirst-data-postalcode-by-latest.csv records from /pelias/data/whosonfirst/meta
2020-04-07T20:37:08.508Z - info: [whosonfirst] Loading whosonfirst-data-postalcode-ca-latest.csv records from /pelias/data/whosonfirst/meta
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: ENOENT: no such file or directory, open '/pelias/data/whosonfirst/meta/whosonfirst-data-postalcode-ca-latest.csv'
Emitted 'error' event at:
    at lazyFs.open (internal/fs/streams.js:115:12)
    at FSReqWrap.args [as oncomplete] (fs.js:140:20)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! pelias-whosonfirst@0.0.0-development start: `./bin/start`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the pelias-whosonfirst@0.0.0-development start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ubuntu/.npm/_logs/2020-04-07T20_37_18_186Z-debug.log
```

**Comment by Petah** [comment] 2020-04-23 01:21
Now running the downloaders are not working:

```
error downloading whosonfirst-data-postalcode-za-latest.tar.bz2 bundle: Error: Command failed: curl -s https://dist.whosonfirst.org/bundles/whosonfirst-data-postalcode-za-latest.tar.bz2 | tar -xj --strip-components=1 --exclude=README.txt -C /pelias/data/whosonfirst && mv /pelias/data/whosonfirst/whosonfirst-data-postalcode-za-latest.csv /pelias/data/whosonfirst/meta
bzip2: (stdin) is not a bzip2 file.
tar: Child returned status 2
tar: Error is not recoverable: exiting now

bzip2: (stdin) is not a bzip2 file.
tar: Child returned status 2
tar: Error is not recoverable: exiting now

All done!
ubuntu@ip-10-0-0-25:/pelias/whosonfirst$ 
ubuntu@ip-10-0-0-25:/pelias/whosonfirst$ wget https://dist.whosonfirst.org/bundles/whosonfirst-data-postalcode-za-latest.tar.bz2
--2020-04-23 01:19:38--  https://dist.whosonfirst.org/bundles/whosonfirst-data-postalcode-za-latest.tar.bz2
Resolving dist.whosonfirst.org (dist.whosonfirst.org)... 99.84.181.34, 99.84.181.70, 99.84.181.120, ...
Connecting to dist.whosonfirst.org (dist.whosonfirst.org)|99.84.181.34|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2020-04-23 01:19:38 ERROR 403: Forbidden.
```

**Comment by Joxit** [comment] 2020-04-23 07:45
Hi @Petah, related to pelias/whosonfirst#487  

> Who's on First has turned off their downloads at dist.whosonfirst.org.

https://github.com/pelias/whosonfirst/pull/487#issuecomment-615387185
