### ISSUE TITLE
Search for "Dundee" shows place in USA as first result

### ISSUE THREAD

**Issue by boothym** [pelias/pelias#526] opened 2017-03-28 10:58 UTC
I was directed here from this Mapillary issue: https://github.com/mapillary/mapillary_issues/issues/2423

---
#### Here's what I did :innocent:
Type "Dundee" into Mapillary or the Mapzen search - the city of Dundee in Scotland (population ~150,000) appears second in the list. The same thing happens with "Stirling" and "Inverness"
(http://pelias.io/compare doesn't work btw)

---
#### Here's what I got :scream_cat:
https://mapzen.com/products/search/?query=dundee&endpoint=search&lng=-73.98073&lat=40.72606&zoom=12

---
#### Here's what I was expecting :sparkles:
I expected the city of Dundee, Scotland to appear first in the search results. 

---
#### Here's what I think could be improved :trophy:
Surely there should be some sort of sorting by city/town/village status and population taken into account if known?

**Comment by missinglink** [comment] 2017-04-04 13:42
I can confirm this is a bug based, the sorting should be `geonames:locality:2650752` first and then whosonfirst:neighbourhood:85867055 second:

based on:

http://www.geonames.org/2650752/dundee.html
population : 151592

https://whosonfirst.mapzen.com/spelunker/id/85867055
pop10: 11216

additionally the `geonames` record appears to have better term-frequency than the `whosonfirst` record.

will require some query analysis to determine why it's being sorted in this order.

**Comment by missinglink** [comment] 2017-04-04 13:44
interestingly, using the autocomplete endpoint as per `/v1/autocomplete?text=dundee` returns the correct ordering.

**Comment by boothym** [comment] 2017-04-04 14:31
Thanks for responding. I noticed that as well, however other cities like Stirling and Inverness were not the at the top when using the autocomplete.
Also, when searching for Perth, it's understandable Perth, Australia was top of the list - however Perth, Scotland should probably be higher.

**Comment by missinglink** [comment] 2017-04-19 12:20
hi @boothym I found a problem with the function which aggregates population data, basically there are a bunch of fields in our source data which could contain population info and we weren't checking them all.

I checked with the data team and revised the function: https://github.com/pelias/whosonfirst/pull/221

hopefully that helps, this will take a week or two to make it through review, staging and deployment but we can continue tracking it here, I'll let you know again when I have more info.

**Comment by missinglink** [comment] 2017-05-30 17:00
added population info in https://github.com/whosonfirst-data/whosonfirst-data/commit/20c709825c386bbe55c145b05648e363b28ca7ae

**Comment by boothym** [comment] 2017-07-27 14:26
Thanks @missinglink, looks like it has been sorted in the mapillary search box. However, both Stirling and Inverness are not first in their lists, so maybe you could sort those as well?

Also, when I entered "Dundee" etc on https://mapzen.com/products/search/ to check if it was working, it did not appear at all in the list!

**Comment by missinglink** [comment] 2017-07-31 13:16
hey @boothym, you're right that `Dundee` isn't coming up on the mapzen docs page, this is due to it defaulting to a view of the USA and using a location bias, so it's favoring American results higher.

doing a basic `/v1/search?text=dundee` now shows it coming in at tenth:

```bash
 1)	Dundee, South Africa
 2)	Dundee, IL, USA
 3)	Dundee, MI, USA
 4)	Dundee, Omaha, NE, USA
 5)	Dundee, FL, USA
 6)	Dundee, MI, USA
 7)	Dundee, OR, USA
 8)	Dundee, NY, USA
 9)	Dundee, OH, USA
10)	Dundee, Scotland, United Kingdom
```

so.. that's better but still not correct. cc/ @trescube I fixed the population for `Dundee, Scotland, united Kingdom` but it's still not scoring a highly as I would like, is it possible that the controller-level scoring rules are causing this?

**Comment by missinglink** [comment] 2017-07-31 13:18
re: Stirling and Inverness, I would prefer not to manually edit all the populations, I heard new from the whosonfirst team that they are nearly finished with a re-import of geonames which should bring in the missing population counts for allthethings.

**Comment by missinglink** [comment] 2017-08-02 12:52
hi @boothym I'm still following up with ways of improving the population coverage through bulk imports with the data team.

it looks like it might take some time so I went ahead and added Stirling and Inverness for you manually.

**Comment by trescube** [comment] 2017-08-02 13:42
Placeholder must be running on an old data build since the cached record lacks a `population` field for Dundee, UK whereas the [Who's on First](https://whosonfirst.mapzen.com/spelunker/id/101750641) record does.  This is only useful for @missinglink but here's the Placeholder call that shows no population for that record:

http://pelias-prod-placeholder-251874426.us-east-1.elb.amazonaws.com/parser/search?text=dundee

**Comment by trescube** [comment] 2017-08-02 13:44
The Pelias [sorting module](https://www.npmjs.com/package/pelias-sorting) treats localities with [no population field as population 0](https://github.com/pelias/sorting/blob/master/index.js#L44).

**Comment by boothym** [comment] 2017-08-11 15:07
@missinglink Thanks for doing this. Suppose I'm a little bit confused why you don't import population data and place importance details from OSM?

**Comment by orangejulius** [comment] 2017-09-29 15:42
We have a new data build for Placeholder coming soon, and it gets this correct. We'll update when it's on production!

**Comment by orangejulius** [comment] 2017-09-29 20:52
Okay, that new data is now out on Mapzen Search, so Mapillary should show improved results now.

![image](https://user-images.githubusercontent.com/111716/31035571-7c2e5d6a-a536-11e7-8305-cfaab9121083.png)
http://pelias.github.io/compare/#/v1/search%3Ftext=dundee

I think this issue is now fixed but if there's anything missing, please let us know!

**Closed by orangejulius** 2017-09-29 20:52 UTC
Labels: outreach
