### ISSUE TITLE
Setup recurring interpolation build

### ISSUE THREAD

**Issue by dianashk** [pelias/pelias#503] opened 2017-02-13 16:53 UTC
- [x] writeup proposal for needed infrastructure improvements and the end-goal of this task
- [x] research how to best implement what is needed
- [x] implement it
- [ ] high-five everyone!

Connects pelias/pelias#468
Connects pelias/interpolation#7

**Comment by dianashk** [comment] 2017-02-24 14:51
We've decided to implement this recurring build setup using our current Chef framework and avoid introducing new technologies at this time. We will revisit all of our infrastructure in Q2-17 and make decisions about new technology then.

**Comment by dianashk** [comment] 2017-04-20 23:25
What's left here before we can high-five everyone? 👏

**Comment by orangejulius** [comment] 2017-04-26 20:32
I currently have a shell script that sets up an interpolation build from scratch. There's a build currently running and it looks great. However, it will take several days to run still before we know for sure. @missinglink and I have been discussing how to speed up the build and we have some ideas. That might help us get it out faster.

**Comment by orangejulius** [comment] 2017-06-15 16:23
**UPDATE!** I have been working on these automated builds for a while sporadically when i have time. The script for automated builds is, I think, almost done, but making progress has been slow because the builds take a very long time. The build that is currently running, for example, started on June 6th. So it's been running now for almost 10 days.

**Comment by orangejulius** [comment] 2017-07-27 18:51
Duplicate of https://github.com/pelias/pelias/issues/468

**Closed by orangejulius** 2017-07-27 18:51 UTC
Labels: in progress
