### ISSUE TITLE
Setting a Custom Whosonfirst Source

### ISSUE THREAD

**Issue by Namec** [pelias/pelias#742] opened 2018-08-27 13:53 UTC
Hello All,

is it possible to set a custom Whosonfirst source hosted locally and make the geocoder use for reverse geocoding.

Thank you

**Comment by missinglink** [comment] 2018-08-28 11:45
Hi @Namec 

I'm not sure if I understand the question, could you please explain a little more about what you'd like to achieve by doing this?

Are you saying you have a custom polygon dataset that you would like to use as an alternative to `whosonfirst`?

**Comment by Namec** [comment] 2018-08-29 11:59
Hello@missinglink

this is Exactly what i am saying, have a custom polygon dataset that i would like to use as an alternative to whosonfirst.

any idea how to manage this

**Comment by missinglink** [comment] 2018-08-29 15:31
If you convert your dataset to use the same conventions as whosonfirst it would 'just work'.

In order to do this, you would need to ensure that the file naming conventions, json properties and placetype associations were the same as in whosonfirst.

Which dataset would you like to use instead?

**Comment by orangejulius** [comment] 2018-09-10 19:31
Closing as this is a dupe of https://github.com/pelias/pelias/issues/741

**Closed by orangejulius** 2018-09-10 19:31 UTC
