### ISSUE TITLE
Administrative hierarchy data in pelias

### ISSUE THREAD

**Issue by MALKARAJ** [pelias/pelias#969] opened 2024-06-05 11:22 UTC
Hi Team,
I appreciate your efforts in answering every query and providing support for Pelias
**,is there any way to get administrative hierarchy data using Pelias**

for example
**country -> state -> city-> next subdivision**

Thanks,
Malkaraj K

**Comment by mtmail** [comment] 2024-06-05 14:02
I believe that's a duplicate of https://community.openstreetmap.org/t/is-it-possible-to-get-administrative-hierarchy-data-in-osm-using-overpass-api/114135

**Comment by arnesetzer** [comment] 2024-11-21 10:23
You can use the [wof](https://github.com/pelias/whosonfirst/) data which provides this feature. Alternatively you may wanna have a look on https://github.com/pelias/spatial

**Comment by missinglink** [comment] 2024-11-21 11:17
For individual records the `/v1/reverse` API will return the administrative hierarchy per-feature.

If you grab one of the WOF SQLite downloads from here you will find a table called `ancestors` which contains this information for all places.

https://geocode.earth/data/whosonfirst/

**Closed by missinglink** 2024-11-21 11:17 UTC
Labels: enhancement
