### ISSUE TITLE
Missing Localities

### ISSUE THREAD

**Issue by shoxter** [pelias/pelias#553] opened 2017-04-25 11:56 UTC
Hey team! 

I was using your awesome geocoding engine when I noticed something interesting.
Let me tell you more about it.

---

[`/v1/autocomplete?text=3235 cyp&focus.point.lat=29.1119268&focus.point.lon=-81.0368103&layers=address`
](http://pelias.github.io/compare/#/v1/autocomplete%3Ffocus.point.lat=29.1119268&focus.point.lon=-81.0368103&layers=address&text=3235%20cyp)

or

[`/v1/autocomplete?focus.point.lat=29.1119268&focus.point.lon=-81.0368103&layers=address&text=2100 st`](http://pelias.github.io/compare/#/v1/autocomplete%3Ffocus.point.lat=29.1119268&focus.point.lon=-81.0368103&layers=address&text=2100%20st)

---
Results were respectively:

<details>
<summary>for 3235 cyp</summary>

```
{
  "geocoding": {
    "version": "0.2",
    "attribution": "https:\/\/search.mapzen.com\/v1\/attribution",
    "query": {
      "text": "3235 cyp",
      "tokens": [
        "3235",
        "cyp"
      ],
      "size": 10,
      "layers": [
        "address"
      ],
      "private": false,
      "focus.point.lat": 29.1119268,
      "focus.point.lon": -81.0368103,
      "lang": {
        "name": "English",
        "iso6391": "en",
        "iso6393": "eng",
        "defaulted": false
      }
    },
    "engine": {
      "name": "Pelias",
      "author": "Mapzen",
      "version": "1.0"
    },
    "timestamp": 1493121251552
  },
  "type": "FeatureCollection",
  "features": [
    {
      "type": "Feature",
      "geometry": {
        "type": "Point",
        "coordinates": [
          -81.757376,
          26.213042
        ]
      },
      "properties": {
        "id": "us\/fl\/collier:e5258a58baa3d7cc",
        "gid": "openaddresses:address:us\/fl\/collier:e5258a58baa3d7cc",
        "layer": "address",
        "source": "openaddresses",
        "source_id": "us\/fl\/collier:e5258a58baa3d7cc",
        "name": "3235 Cypress Glen Way",
        "housenumber": "3235",
        "street": "Cypress Glen Way",
        "distance": 329.008,
        "accuracy": "point",
        "country": "United States",
        "country_gid": "whosonfirst:country:85633793",
        "country_a": "USA",
        "region": "Florida",
        "region_gid": "whosonfirst:region:85688651",
        "region_a": "FL",
        "county": "Collier County",
        "county_gid": "whosonfirst:county:102085853",
        "neighbourhood": "Falls of Naples",
        "neighbourhood_gid": "whosonfirst:neighbourhood:420511713",
        "label": "3235 Cypress Glen Way, Collier County, FL, USA"
      }
    },
    {
      "type": "Feature",
      "geometry": {
        "type": "Point",
        "coordinates": [
          -81.757214,
          26.21282
        ]
      },
      "properties": {
        "id": "us\/fl\/collier:d0f607102ee4be0c",
        "gid": "openaddresses:address:us\/fl\/collier:d0f607102ee4be0c",
        "layer": "address",
        "source": "openaddresses",
        "source_id": "us\/fl\/collier:d0f607102ee4be0c",
        "name": "3235 Cypress Glen Way",
        "housenumber": "3235",
        "street": "Cypress Glen Way",
        "distance": 329.028,
        "accuracy": "point",
        "country": "United States",
        "country_gid": "whosonfirst:country:85633793",
        "country_a": "USA",
        "region": "Florida",
        "region_gid": "whosonfirst:region:85688651",
        "region_a": "FL",
        "county": "Collier County",
        "county_gid": "whosonfirst:county:102085853",
        "neighbourhood": "Cypress Glen",
        "neighbourhood_gid": "whosonfirst:neighbourhood:420511697",
        "label": "3235 Cypress Glen Way, Collier County, FL, USA"
      }
    }
  ],
  "bbox": [
    -81.757376,
    26.21282,
    -81.757214,
    26.213042
  ]
}
```

</details>

and

<details>
<summary>for `2100 st`</summary>

```
{
  "geocoding": {
    "version": "0.2",
    "attribution": "https:\/\/search.mapzen.com\/v1\/attribution",
    "query": {
      "text": "2100 str",
      "tokens": [
        "2100",
        "str"
      ],
      "size": 10,
      "layers": [
        "address"
      ],
      "private": false,
      "focus.point.lat": 29.1119268,
      "focus.point.lon": -81.0368103,
      "lang": {
        "name": "English",
        "iso6391": "en",
        "iso6393": "eng",
        "defaulted": false
      }
    },
    "engine": {
      "name": "Pelias",
      "author": "Mapzen",
      "version": "1.0"
    },
    "timestamp": 1493121283493
  },
  "type": "FeatureCollection",
  "features": [
    {
      "type": "Feature",
      "geometry": {
        "type": "Point",
        "coordinates": [
          -81.288788,
          28.990887
        ]
      },
      "properties": {
        "id": "us\/fl\/volusia:716ced4097e52bd9",
        "gid": "openaddresses:address:us\/fl\/volusia:716ced4097e52bd9",
        "layer": "address",
        "source": "openaddresses",
        "source_id": "us\/fl\/volusia:716ced4097e52bd9",
        "name": "2100 Stratford Dr",
        "housenumber": "2100",
        "street": "Stratford Dr",
        "postalcode": "32724",
        "distance": 27.968,
        "accuracy": "point",
        "country": "United States",
        "country_gid": "whosonfirst:country:85633793",
        "country_a": "USA",
        "region": "Florida",
        "region_gid": "whosonfirst:region:85688651",
        "region_a": "FL",
        "county": "Volusia County",
        "county_gid": "whosonfirst:county:102085865",
        "label": "2100 Stratford Dr, Volusia County, FL, USA"
      }
    },
    {
      "type": "Feature",
      "geometry": {
        "type": "Point",
        "coordinates": [
          -81.406013,
          28.502654
        ]
      },
      "properties": {
        "id": "us\/fl\/orange_county:9237df98870a8ea3",
        "gid": "openaddresses:address:us\/fl\/orange_county:9237df98870a8ea3",
        "layer": "address",
        "source": "openaddresses",
        "source_id": "us\/fl\/orange_county:9237df98870a8ea3",
        "name": "2100 40th Street",
        "housenumber": "2100",
        "street": "40th Street",
        "postalcode": "32839",
        "distance": 76.543,
        "accuracy": "point",
        "country": "United States",
        "country_gid": "whosonfirst:country:85633793",
        "country_a": "USA",
        "region": "Florida",
        "region_gid": "whosonfirst:region:85688651",
        "region_a": "FL",
        "county": "Orange County",
        "county_gid": "whosonfirst:county:102085847",
        "neighbourhood": "Park Central",
        "neighbourhood_gid": "whosonfirst:neighbourhood:85879507",
        "label": "2100 40th Street, Orange County, FL, USA"
      }
    },
    {
      "type": "Feature",
      "geometry": {
        "type": "Point",
        "coordinates": [
          -81.495308,
          28.509648
        ]
      },
      "properties": {
        "id": "us\/fl\/orange_county:c2c5cf734f30fb7f",
        "gid": "openaddresses:address:us\/fl\/orange_county:c2c5cf734f30fb7f",
        "layer": "address",
        "source": "openaddresses",
        "source_id": "us\/fl\/orange_county:c2c5cf734f30fb7f",
        "name": "2100 Stillington Street",
        "housenumber": "2100",
        "street": "Stillington Street",
        "postalcode": "32835",
        "distance": 80.368,
        "accuracy": "point",
        "country": "United States",
        "country_gid": "whosonfirst:country:85633793",
        "country_a": "USA",
        "region": "Florida",
        "region_gid": "whosonfirst:region:85688651",
        "region_a": "FL",
        "county": "Orange County",
        "county_gid": "whosonfirst:county:102085847",
        "neighbourhood": "Metro West",
        "neighbourhood_gid": "whosonfirst:neighbourhood:85866883",
        "label": "2100 Stillington Street, Orange County, FL, USA"
      }
    },
    {
      "type": "Feature",
      "geometry": {
        "type": "Point",
        "coordinates": [
          -81.353968,
          28.427171
        ]
      },
      "properties": {
        "id": "us\/fl\/orange_county:bcb8b99b2f81be1a",
        "gid": "openaddresses:address:us\/fl\/orange_county:bcb8b99b2f81be1a",
        "layer": "address",
        "source": "openaddresses",
        "source_id": "us\/fl\/orange_county:bcb8b99b2f81be1a",
        "name": "2100 4th Street",
        "housenumber": "2100",
        "street": "4th Street",
        "postalcode": "32824",
        "distance": 81.969,
        "accuracy": "point",
        "country": "United States",
        "country_gid": "whosonfirst:country:85633793",
        "country_a": "USA",
        "region": "Florida",
        "region_gid": "whosonfirst:region:85688651",
        "region_a": "FL",
        "county": "Orange County",
        "county_gid": "whosonfirst:county:102085847",
        "locality": "Orlando",
        "locality_gid": "whosonfirst:locality:85933091",
        "neighbourhood": "Boggy Creek",
        "neighbourhood_gid": "whosonfirst:neighbourhood:85879421",
        "label": "2100 4th Street, Orlando, FL, USA"
      }
    },
    {
      "type": "Feature",
      "geometry": {
        "type": "Point",
        "coordinates": [
          -81.355194,
          28.563149
        ]
      },
      "properties": {
        "id": "us\/fl\/orange_county:f9d2055e9af4cdf0",
        "gid": "openaddresses:address:us\/fl\/orange_county:f9d2055e9af4cdf0",
        "layer": "address",
        "source": "openaddresses",
        "source_id": "us\/fl\/orange_county:f9d2055e9af4cdf0",
        "name": "2100 Linda Street",
        "housenumber": "2100",
        "street": "Linda Street",
        "postalcode": "32803",
        "distance": 68.299,
        "accuracy": "point",
        "country": "United States",
        "country_gid": "whosonfirst:country:85633793",
        "country_a": "USA",
        "region": "Florida",
        "region_gid": "whosonfirst:region:85688651",
        "region_a": "FL",
        "county": "Orange County",
        "county_gid": "whosonfirst:county:102085847",
        "locality": "Orlando",
        "locality_gid": "whosonfirst:locality:85933091",
        "neighbourhood": "Colonialtown North",
        "neighbourhood_gid": "whosonfirst:neighbourhood:85879435",
        "label": "2100 Linda Street, Orlando, FL, USA"
      }
    },
    {
      "type": "Feature",
      "geometry": {
        "type": "Point",
        "coordinates": [
          -81.355186,
          28.561532
        ]
      },
      "properties": {
        "id": "us\/fl\/orange_county:98716fce1af73ee6",
        "gid": "openaddresses:address:us\/fl\/orange_county:98716fce1af73ee6",
        "layer": "address",
        "source": "openaddresses",
        "source_id": "us\/fl\/orange_county:98716fce1af73ee6",
        "name": "2100 Gale Street",
        "housenumber": "2100",
        "street": "Gale Street",
        "postalcode": "32803",
        "distance": 68.459,
        "accuracy": "point",
        "country": "United States",
        "country_gid": "whosonfirst:country:85633793",
        "country_a": "USA",
        "region": "Florida",
        "region_gid": "whosonfirst:region:85688651",
        "region_a": "FL",
        "county": "Orange County",
        "county_gid": "whosonfirst:county:102085847",
        "locality": "Orlando",
        "locality_gid": "whosonfirst:locality:85933091",
        "neighbourhood": "Colonialtown North",
        "neighbourhood_gid": "whosonfirst:neighbourhood:85879435",
        "label": "2100 Gale Street, Orlando, FL, USA"
      }
    },
    {
      "type": "Feature",
      "geometry": {
        "type": "Point",
        "coordinates": [
          -81.35518,
          28.560701
        ]
      },
      "properties": {
        "id": "us\/fl\/orange_county:5f8fae39622eeca6",
        "gid": "openaddresses:address:us\/fl\/orange_county:5f8fae39622eeca6",
        "layer": "address",
        "source": "openaddresses",
        "source_id": "us\/fl\/orange_county:5f8fae39622eeca6",
        "name": "2100 Vivada Street",
        "housenumber": "2100",
        "street": "Vivada Street",
        "postalcode": "32803",
        "distance": 68.541,
        "accuracy": "point",
        "country": "United States",
        "country_gid": "whosonfirst:country:85633793",
        "country_a": "USA",
        "region": "Florida",
        "region_gid": "whosonfirst:region:85688651",
        "region_a": "FL",
        "county": "Orange County",
        "county_gid": "whosonfirst:county:102085847",
        "locality": "Orlando",
        "locality_gid": "whosonfirst:locality:85933091",
        "neighbourhood": "Colonialtown North",
        "neighbourhood_gid": "whosonfirst:neighbourhood:85879435",
        "label": "2100 Vivada Street, Orlando, FL, USA"
      }
    },
    {
      "type": "Feature",
      "geometry": {
        "type": "Point",
        "coordinates": [
          -81.355012,
          28.559843
        ]
      },
      "properties": {
        "id": "us\/fl\/orange_county:48d055c984e22fbf",
        "gid": "openaddresses:address:us\/fl\/orange_county:48d055c984e22fbf",
        "layer": "address",
        "source": "openaddresses",
        "source_id": "us\/fl\/orange_county:48d055c984e22fbf",
        "name": "2100 Oregon Street",
        "housenumber": "2100",
        "street": "Oregon Street",
        "postalcode": "32803",
        "distance": 68.618,
        "accuracy": "point",
        "country": "United States",
        "country_gid": "whosonfirst:country:85633793",
        "country_a": "USA",
        "region": "Florida",
        "region_gid": "whosonfirst:region:85688651",
        "region_a": "FL",
        "county": "Orange County",
        "county_gid": "whosonfirst:county:102085847",
        "locality": "Orlando",
        "locality_gid": "whosonfirst:locality:85933091",
        "neighbourhood": "Colonialtown North",
        "neighbourhood_gid": "whosonfirst:neighbourhood:85879435",
        "label": "2100 Oregon Street, Orlando, FL, USA"
      }
    },
    {
      "type": "Feature",
      "geometry": {
        "type": "Point",
        "coordinates": [
          -81.355013,
          28.551993
        ]
      },
      "properties": {
        "id": "us\/fl\/orange_county:d5d58edcc36a6776",
        "gid": "openaddresses:address:us\/fl\/orange_county:d5d58edcc36a6776",
        "layer": "address",
        "source": "openaddresses",
        "source_id": "us\/fl\/orange_county:d5d58edcc36a6776",
        "name": "2100 Hillcrest Street",
        "housenumber": "2100",
        "street": "Hillcrest Street",
        "postalcode": "32803",
        "distance": 69.396,
        "accuracy": "point",
        "country": "United States",
        "country_gid": "whosonfirst:country:85633793",
        "country_a": "USA",
        "region": "Florida",
        "region_gid": "whosonfirst:region:85688651",
        "region_a": "FL",
        "county": "Orange County",
        "county_gid": "whosonfirst:county:102085847",
        "locality": "Orlando",
        "locality_gid": "whosonfirst:locality:85933091",
        "neighbourhood": "Colonialtown South",
        "neighbourhood_gid": "whosonfirst:neighbourhood:85879437",
        "label": "2100 Hillcrest Street, Orlando, FL, USA"
      }
    },
    {
      "type": "Feature",
      "geometry": {
        "type": "Point",
        "coordinates": [
          -81.355018,
          28.551084
        ]
      },
      "properties": {
        "id": "us\/fl\/orange_county:ba1ad2928e38db26",
        "gid": "openaddresses:address:us\/fl\/orange_county:ba1ad2928e38db26",
        "layer": "address",
        "source": "openaddresses",
        "source_id": "us\/fl\/orange_county:ba1ad2928e38db26",
        "name": "2100 E Concord Street",
        "housenumber": "2100",
        "street": "E Concord Street",
        "postalcode": "32803",
        "distance": 69.486,
        "accuracy": "point",
        "country": "United States",
        "country_gid": "whosonfirst:country:85633793",
        "country_a": "USA",
        "region": "Florida",
        "region_gid": "whosonfirst:region:85688651",
        "region_a": "FL",
        "county": "Orange County",
        "county_gid": "whosonfirst:county:102085847",
        "locality": "Orlando",
        "locality_gid": "whosonfirst:locality:85933091",
        "neighbourhood": "Colonialtown South",
        "neighbourhood_gid": "whosonfirst:neighbourhood:85879437",
        "label": "2100 E Concord Street, Orlando, FL, USA"
      }
    }
  ],
  "bbox": [
    -81.495308,
    28.427171,
    -81.288788,
    28.990887
  ]
}
```

</details>

---
The issue with these searches (and it looks like it's more than just these two) is that the locality (Naples and DeLand respectively) are missing and thus, the county is being show instead. Also, the former search seems to be returning the same address twice. Is there a way we can narrow down what is causing this and fix it? I just started using Mapzen yesterday and would be happy to assist, I just am not sure where to begin.

Thanks!

*** updated to protect user's API key ***

**Comment by dianashk** [comment] 2017-04-25 13:02
Hey @shoxter,
Welcome to Mapzen Search and thank you for filing this issue! We really appreciate feedback from our users and would love to help you contribute to the project if that's something you're interested in doing.
What you're seeing with these missing localities is most likely a data issue. We currently use data from the [Who's on First (WOF) gazetteer](whosonfirst.mapzen.com) to look up which administrative areas all address points belong to. This is done with point-in-polygon checks. In the case of `Naples` and your first query, I would assume you're expecting [this WOF record](https://whosonfirst.mapzen.com/spelunker/id/85931799) to be listed as the locality. But if we [center that map on the point where the address lies](https://whosonfirst.mapzen.com/spelunker/id/85931799/#13/26.213042/-81.757376), you can see that it falls just outside of the region we consider to be Naples. 

So to help fix this issue you could suggest an update to the WOF record in github, if it is indeed incorrect. If the geometry is correct, then what we're looking at is probably related to a known issue we call [`Postal Cities`](https://github.com/pelias/pelias/issues?q=is%3Aopen+is%3Aissue+milestone%3A%22Postal+Cities%22) where the postal address people use does not actually correspond to the valid geometries of the region. We don't have a solution for that issue yet, but any feedback on it would be appreciated.

Cheers! 👋

**Comment by shoxter** [comment] 2017-04-25 13:43
@dianashk Just to be sure I understand -- is the implication that US addresses have the possibility of containing no locality at all? 

I was under the impression that if a location wasn't in one locality, it had to be in another. Is that a false assumption? Is it possible for there to be geographical gaps in between localities which effectively render the addresses within those gaps "cityless?"

I'm just trying to make sure I understand the issue before moving forward. Our end users will expect the addresses to have localities, and I want to make sure this is something I can help address before moving forward. 

Thank you!

**Comment by dianashk** [comment] 2017-04-25 17:30
From a geometry standpoint, that is correct. Some addresses don't fall within actual boundaries of any locality. However, the post office still assigns them cities, which is not represented on a map.

You can [track this issue here](https://github.com/whosonfirst-data/whosonfirst-data/issues/202) from the data side of things.

**Comment by shoxter** [comment] 2017-04-25 17:41
@dianashk Got it. 

Do we know how services like Google Maps associates these "cityless" addresses with the "USPS correct" city?

**Comment by dianashk** [comment] 2017-04-25 17:48
As mentioned in the linked issue from WOF:

>This can be derived from the ZCTA from US Census and looking at the locality name.

Speaking with @nvkelso, this might be something we get in the next few months! 👏  👏  👏

**Comment by orangejulius** [comment] 2019-03-05 21:49
Closing as a duplicate of https://github.com/pelias/pelias/issues/396

**Closed by orangejulius** 2019-03-05 21:49 UTC
Labels: outreach
