### ISSUE TITLE
Tokyo, Japan takes you too far off the coast of Japan

### ISSUE THREAD

**Issue by clhenrick** [pelias/pelias#397] opened 2016-08-05 00:25 UTC
![screen shot 2016-08-04 at 5 23 39 pm](https://cloud.githubusercontent.com/assets/161748/17422600/5f1a804c-5a68-11e6-950c-0cbb95744b93.png)

**Comment by orangejulius** [comment] 2016-08-05 14:10
Hey @clhenrick!

We just discovered this exact issue the other day. You can read all the details at https://github.com/pelias/pelias/issues/370. Since that ticket was opened it looks like Who's on First has added improved bounding boxes for Tokyo and SF, and we could now write some code to take advantage of it.

That code would make it out into our next build, and would be released either next week or the week after!

**Comment by clhenrick** [comment] 2016-08-05 15:50
Awesome, thanks Julian!

-Chris
clhenrick.io

**Comment by clhenrick** [comment] 2016-08-08 20:13
@orangejulius on a totally tangential note this issue made me think about how Natural Earth uses admin1 polygons that don't include ocean areas; the rationale being it's a more suited convention for cartographic design. 

It's making me wonder if the Who's On First data is also taking cartography into consideration, or is it more intended for analysis, geocoding, etc.?

**Comment by orangejulius** [comment] 2016-08-08 20:16
Funny you should ask! There is a ticket to discuss [this exact problem](https://github.com/whosonfirst-data/whosonfirst-data/issues/367)

**Comment by clhenrick** [comment] 2016-08-08 20:45
I guess my question is more along the lines of are geometries and features in Who's On First being categorized so that they're identifiable for rendering at certain map scale / zoom levels, similar to how NE has 3 levels of generalization (1:10m, 1:50m, 1:110m) as well as a `scalerank` field?

**Comment by orangejulius** [comment] 2016-08-09 18:20
This is a good question that I don't have a good answer to, I'd suggest asking the Who's on First team [directly](https://github.com/whosonfirst-data/whosonfirst-data/issues).

**Comment by dianashk** [comment] 2016-08-18 19:21
@nvkelso, any to add here?

**Comment by nvkelso** [comment] 2016-08-18 22:46
Hi @clhenrick! Looks like @orangejulius fix is in Pelias prod now :) Suggest this issue should be closed (it was a duplicate of https://github.com/pelias/pelias/issues/370).

W/r/t the tangential question, we're tracking related work in https://github.com/whosonfirst-data/whosonfirst-data/issues/367, which is thinking about thumbnail previews and reverse geocoding but there could be something down the line about using the Natural Earth alt geometry at such and such zooms.

**Comment by thisisaaronland** [comment] 2016-08-18 23:35
@clhenrick – The short answer to your question is: Yes. The longer answer to your question is: It hasn't happened yet so if you have suggestions or specific needs we'd love to hear them. The long answer is: https://mapzen.com/blog/mapping-with-bias/#geometries

**Comment by orangejulius** [comment] 2016-08-19 19:54
This is definitely now fixed :) Thanks everyone for chiming in to answer Chris's question.

**Closed by orangejulius** 2016-08-19 19:54 UTC
Labels: in review

**Comment by clhenrick** [comment] 2016-08-19 20:02
Thanks @orangejulius @nvkelso @thisisaaronland for the thoughtful replies. I think it would be great if Who's On First supported geometry recommendations for zoom level / map scale. Looking forward to reading the blog post as well.
